### ISSUE TITLE
all positions "missing"

### ISSUE THREAD

**Issue by mutundis** [PharmGKB/PharmCAT#10]
Hi,

I would like to try this out but unfortunately can't get going. After installation I can run the program like this:

java -cp build/libs/pharmcat-*-all.jar org.pharmgkb.pharmcat.haplotype.NamedAlleleMatcher -d ../cpic-data/generatedDefinitions -html /tmp/test.html -json /tmp/test.json -vcf src/test/resources/org/pharmgkb/pharmcat/haplotype/NA12878.2c19_filtered.vcf
Printing to /tmp/test.html

but  in the output html every site is reported as "missing". Same with various other VCF inputs that I've tried.

Thanks for any help.

java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

OS X 10.11.6 (15G1217)

**Comment by lester-pharmgkb** [comment]
You need to prepare the input vcf according to the instructions given in:
[https://github.com/PharmGKB/PharmCAT/wiki/Preparing-VCF-Files](https://github.com/PharmGKB/PharmCAT/wiki/Preparing-VCF-Files)

In particular you need to make sure that you are using build grc38 and the indels are formatted the way PharmCAT expects.

**Comment by lester-pharmgkb** [comment]
Actually after re-reading your question again I see you were using one of our example datasets.  Let me try to replicate the issue and investigate further.

**Comment by lester-pharmgkb** [comment]
We've identified the issue and are working on it now.  Check [https://github.com/PharmGKB/PharmCAT/issues/11](https://github.com/PharmGKB/PharmCAT/issues/11) for progress.

**Comment by lester-pharmgkb** [comment]
We are in the process of updating the prepacked zip/gz files, however you should now be able to download the [cpic definitions](https://github.com/PharmGKB/cpic-data) and run the NamedAlleleMatcher.

**Comment by whaleyr** [comment]
Issue #11 has been resolved so this should work now too. The named allele definitions are not included in the codebase and should be functioning properly.

**Comment by mutundis** [comment]
working for me, thanks!
