### ISSUE TITLE
Preprocessor --missing_to_ref argument incorrect phasing

### ISSUE THREAD

**Issue by anh151** [PharmGKB/PharmCAT#102]
Hi Binglan. We talked about this, but I wanted to give you an example of the behavior. 

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
When using the "--missing_to_ref" argument in the preprocessor with an unphased input, the output vcf is phased for the variants not in the input vcf and unphased for the variants that are in the input file. Additionally, in the html report from PharmCAT the phasing status is reported as "phased" if no variants are detected.

* **If the current behavior is a bug, please provide the steps to reproduce and, if possible, your example input data** via a [Gist](https://gist.github.com) or similar.
Here is an example of a very simple single sample vcf with only 1 variant listed for CYP2C19 that is hom ref. 
![image](https://user-images.githubusercontent.com/55815040/168400255-3ae7d36b-92da-49b2-a9e2-52b94ac2c61d.png)

Running the following command with preprocessor
```bash
python3 ./preprocessor/PharmCAT_VCF_Preprocess.py \
--input_vcf ./test.vcf \
--ref_pgx_vcf ./preprocessor/pharmcat_positions.vcf.bgz \
--ref_seq ./PharmCAT/src/scripts/test/pharmcat_pgx_vcf/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna \
--missing_to_ref \
--output_prefix ready \
--output_folder test
```
This produces the following vcf file where variants in the original file are unphased and missing variants are phased.
![image](https://user-images.githubusercontent.com/55815040/168401320-5234fc0c-f5e1-4dac-a038-48e3e8fa36e7.png)

Running the following command with PharmCAT
```bash
./java/jdk-14.0.2+12/bin/java \
-jar ./PharmCAT/build/libs/pharmcat-1.8.0-2-gae66c5b6-all.jar \
-vcf ./test/ready.2806550.vcf \
-o test \
-j
```
This produces an html file which shows phased for CYP2C19
![image](https://user-images.githubusercontent.com/55815040/168401053-a4f2ba64-3c6e-4b90-a109-e4cba31f2b19.png)

* **What is the expected behavior?**
I would expect variants to be added as phased/unphased to match the input vcf. Since phasing does not matter for hom ref, the current output of the preprocessor may be appropriate. However, the output from PharmCAT should not state phased if the input vcf contains unphased data.

* **Please tell us about your environment:**
 
  - PharmCAT Version: 1.8.0
  - JDK Version: jdk-14.0.2+12
  - Environment: Linux

**Comment by BinglanLi** [comment]
Thank you Andrew. Nothing regarding this issue has been touched in the VCF preprocessor so it's a change in bcftools' behavior. I'll look into a solution for it.

**Comment by anh151** [comment]
Hey Binglan,
Just wanted to give you a scenario where this actually is a problem. This is the first scenario I have come across where I think it is affecting the calling. 

Consider a sample with the following variants for TPMT:
![image](https://user-images.githubusercontent.com/55815040/189540409-46aaf483-ef7c-4de4-841f-067c114d8fe7.png)

Output from preprocessor using --missing-to-ref is the following:
![image](https://user-images.githubusercontent.com/55815040/189540642-4079f8dc-0e37-4a6d-ada1-d9403508378c.png)

It seems like PharmCAT attempts to resolve the haplotype but can't because one variants is phased and the others are not.
{'gene': 'TPMT', 'chromosome': 'chr6', 'position': 18130687, 'dbSnpId': 'rs1142345', 'call': 'T/C', 'alleles': ['*3A', '*3C', '*41'], 'phased': False, 'wildtypeAllele': 'T', 'mismatch': False, 'warnings': []}

{'gene': 'TPMT', 'chromosome': 'chr6', 'position': 18138969, 'dbSnpId': 'rs144041067', 'call': 'T|C', 'alleles': ['*16', '*22'], 'phased': True, 'wildtypeAllele': 'C', 'mismatch': False, 'warnings': []}

{'gene': 'TPMT', 'chromosome': 'chr6', 'position': 18138997, 'dbSnpId': 'rs1800460', 'call': 'C/T', 'alleles': ['*3A', '*3B'], 'phased': False, 'wildtypeAllele': 'C', 'mismatch': False, 'warnings': []}

Final call from PharmCAT is "not called". Call should be *3A/*16.

Hope this helps.

-Andrew

**Comment by BinglanLi** [comment]
Thank you Andrew. I will look into this immediately.

**Comment by BinglanLi** [comment]
Hi @anh151, I pushed a fix of the issue to the `development` branch. Please feel free to try it out and let me know if the issue persists. Thanks.

**Comment by anh151** [comment]
Looks to be working now! Thanks!
