### ISSUE TITLE
CYP2D6 gene representation

### ISSUE THREAD

**Issue by krukanna** [PharmGKB/PharmCAT#109]
* **Do you want to request a *feature* or report a *bug*?**
feature

* **What is the current behavior?**
In version 1.8 PharmCAT does not analyze the CYP2D6 gene

* **What is the expected behavior?**
I would like to add this gene to my PharmCAT reports. You recommended Astrolabe, but I found information on Astrolabe website that _"Previously available software including VIKING, RUNES, and Astrolabe are no longer maintained and distributed."_ 
Are you planning to add CYP2D6 to the preprocessor or need to look for another tool? If so, do you know when the release will be?

* **Please tell us about your environment:**
  
  - PharmCAT Version: 1.8.0

**Comment by whaleyr** [comment]
Experimental CYP2D6 support will be added to the 2.0 release. It will not be enabled by default but you can set a CLI flag to turn on the feature if you're willing to understand the caveats and limitations (which will be documented on the pharmcat.org site). We don't have a set date for the release of 2.0 but the plan is to release "soon".

**Comment by BinglanLi** [comment]
In addition to the experimental CYP2D6 support in v2.0, if you have access to whole genome sequencing (WGS) CRAM/BAM files, we encourage you to use a tool that can take advantage of those files (e.g. Stargazer, StellarPGx, etc.) in order to be able to detect copy number variation and structural variation, which is necessary to get accurate CYP2D6 diplotypes to use clinically. Please see our documentation about CYP2D6 calling (https://pharmcat.org/technical-docs/calling-cyp2d6/).

**Comment by krukanna** [comment]
Hi, thank You for your response.
I decided to use StellarPGx and did all the steps from the instructions on your website. 
The file returned from StellarPGx looks like this:

> CYP2D6 Star Allele Calling with StellarPGx
> Initially computed CN = 17
> Sample core variants:
> 42126611~C>G~1/1;42127941~G>A~0/1;42128945~C>T~0/1;42130692~G>A~0/1;42130761~C>T~0/1
> Candidate alleles:
> ['35.v1_4.v2']
> Result:
> *35/*4x16
> Activity score:
> 1.0
> Metaboliser status:
> Intermediate metaboliser (IM)

So, there is information about Metaboliser status and Activity Score.
However, in the html report there is empty phenotype column (N/A). Additionally, there are no recommendations for drugs that are dependent on this gene.

**Comment by krukanna** [comment]
I will add, that my input file to PharmCAT reporter looks like this:
> CYP2D6	*35/*4x16

It's parsed by your script _stellarPGx_to_PharmCAT.py_
