### ISSUE TITLE
Update json

### ISSUE THREAD

**Issue by lester-pharmgkb** [PharmGKB/PharmCAT#11]
The json schema has been updated, but the current json files do not reflect this.  So for instance old json:

`    {
      "position": 94760676,
      "rsid": "rs113164681",
      "chromosomeHgvsName": "g.94760676C>T",
      "geneHgvsName": "g.2971C>T",
      "proteinNote": "5' region",
      "resourceNote": "-2030C>T",
      "type": "SNP",
      "referenceRepeat": null
    },`

 Verses new json:
`    {
      "chromosome": "chr10",
      "position": 94760676,
      "rsid": "rs113164681",
      "chromosomeHgvsName": "g.94760676C>T",
      "geneHgvsName": "g.2971C>T",
      "proteinNote": "5' region",
      "resourceNote": "-2030C>T Updated position old->new (chr10): 94760676 to 94760676",
      "type": "SNP",
      "referenceRepeat": null
    },`

No positions will map using the old json, whereas it seems to work when I add the chromosomes in, as tested using the following command:

`java -cp PharmCAT/build/libs/pharmcat-*-all.jar org.pharmgkb.pharmcat.haplotype.NamedAlleleMatcher -d generatedDefinitions/ -html test.html -json test.json -vcf PharmCAT/src/test/resources/org/pharmgkb/pharmcat/haplotype/NA12878.2c19_filtered.vcf`

Presumably the zips files will also need updating.

**Comment by whaleyr** [comment]
This was a temporary problem with the JSON named allele definition sheets. It's been fixed and working named allele definitions have been checked into the codebase.
