### ISSUE TITLE
Unable to build docker image

### ISSUE THREAD

**Issue by dheeraj-bobbili1988** [PharmGKB/PharmCAT#110]
* **Do you want to request a *feature* or report a *bug*?**
*bug*

* **What is the current behavior?**
I am trying to build a docker image based on the 2.0 development version. But, it is producing an error.

* **If the current behavior is a bug, please provide the steps to reproduce and, if possible, your example input data** via a [Gist](https://gist.github.com) or similar.

I used the command below
`sudo docker build -t pharmcat2 . --no-cache`

The error that I received.

`Step 44/44 : COPY build/pharmcat.jar ./
lstat build/pharmcat.jar: no such file or directory`

* **Please tell us about your environment:**
  
  - PharmCAT Version: 2.0
  - JDK Version: 17
  - Environment: Linux

**Comment by whaleyr** [comment]
The erorr is telling you that the PharmCAT jar is missing. I'm guessing you haven't compiled the jar before trying to build the docker image.

There are two ways you can go:
1. Follow [the pharmcat docker docs](https://pharmcat.org/technical-docs/docker) and pull the pre-built docker image using `docker pull pgkb/pharmcat`
2. If you _must_ build the image from scratch use the Make script by running `make docker` (that will make sure the jar is compiled and available before it tries to build the docker image)
