### ISSUE TITLE
PharmCAT returning rsid for diplotype calls in SLCO1B1 

### ISSUE THREAD

**Issue by anh151** [PharmGKB/PharmCAT#111]
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
This behavior has only occurred for SLCO1B1. For some samples PharmCAT returns some variation of rs4149056T/rs4149056T, rs4149056C/rs4149056T, or rs4149056C/rs4149056C as the diplotype call. 

* **If the current behavior is a bug, please provide the steps to reproduce and, if possible, your example input data** via a [Gist](https://gist.github.com) or similar.
Consider a sample with the following variants for SLCO1B1. This VCF represents the output from the preprocessor.

#CHROM | POS | REF | ALT | 123456
-- | -- | -- | -- | --
chr12 | 21176804 | A | G | 1/1:.:69:157
chr12 | 21178615 | T | C | 1/1:.:99:213
chr12 | 21239042 | A | C | 0/1:.:48:85

Summarized json output below:
{'diplotypes': ['rs4149056C/rs4149056C'],
 'gene': 'SLCO1B1',
 'variantsOfInterestUnspecified': True,
 'outsideCall': False,
 'totalMissingVariants': 1,
 'totalVariants': 31,
....
'phaseStatus': 'Unphased',
 'extra-position-notes': [],
 'uncalledHaps': '*45',
 'hasUncalledHaps': True,
 'messages': [],
 'unphased': True}

{'gene': 'SLCO1B1', 'chromosome': 'chr12', 'position': 21239042, 'dbSnpId': 'rs34671512', 'call': 'A/C', 'alleles': ['*19', '*20', '*40'], 'phased': False, 'wildtypeAllele': 'A', 'mismatch': False, 'warnings': []}
{'gene': 'SLCO1B1', 'chromosome': 'chr12', 'position': 21176804, 'dbSnpId': 'rs2306283', 'call': 'G|G', 'alleles': ['*14', '*15', '*20', '*24', '*25', '*27', '*28', '*29', '*30', '*31', '*32', '*33', '*37', '*39', '*42', '*43', '*44', '*46', '*47'], 'phased': True, 'wildtypeAllele': 'A', 'mismatch': False, 'warnings': []}
{'gene': 'SLCO1B1', 'chromosome': 'chr12', 'position': 21178615, 'dbSnpId': 'rs4149056', 'call': 'C|C', 'alleles': ['*5', '*15', '*40', '*46', '*47'], 'phased': True, 'wildtypeAllele': 'T', 'mismatch': False, 'warnings': []}

Expected diplotype here would be Indeterminate/Indeterminate which might be reported as "not called" by PharmCAT since this sample has 3 possibilities that all contain 3 alleles (*15/*15/*19;*15/*37/*40;*5/*15/*20)

* **Please tell us about your environment:**
  
  - PharmCAT Version: 1.8.0
  - JDK Version: jdk-14.0.2+12
  - Environment: Linux

Hope this helps. I can provide more examples if needed. This affects ~0.2% of samples. 

Andrew

**Comment by whaleyr** [comment]
This is expected behavior and is documented on our [Gene Definition Exceptions page](https://pharmcat.org/methods/gene-definition-exceptions/#slco1b1).
