### ISSUE TITLE
Preprocessor 2.0.3 - error and Pharmcat 2.0.3 output.

### ISSUE THREAD

**Issue by Pharmacogenetecist** [PharmGKB/PharmCAT#118]
1.
So the good news is that with the HG001 VCF file I shared earlier, the preprocessor seemed to work. Running Pharmcat 2.0.3 then gives one line of err/warning:

chr2:233760233
        Invalid allelic depth (AD) field: 158,132,.,.

and the output .html file is missing several pgx genes. Is this what you get as well? File attached (please change .txt to .html to view).
[HG001.preprocessed.report.txt](https://github.com/PharmGKB/PharmCAT/files/9882231/HG001.preprocessed.report.txt)

2.
With our own vcf data file with the latest 2.0.3 preprocessor (I deleted prior reference files) I get the following error.

 File "/user/Software/PharmCAT-2.0.3/preprocessor/PharmCAT_VCF_Preprocess.py", line 242, in <module>
    run(parsed_args)
  File "/user/Software/PharmCAT-2.0.3/preprocessor/PharmCAT_VCF_Preprocess.py", line 138, in run
    for line in file:
  File "/user/anaconda3/envs/PCAT/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

**Comment by BinglanLi** [comment]
What is the name of your input VCF? What is the full command that you used to run the VCF preprocessor?

**Comment by Pharmacogenetecist** [comment]
> What is the name of your input VCF? What is the full command that you used to run the VCF preprocessor?

Apologies for the delayed response. I notice I get the above error when I use a gvcf. When using a VCF the pre-processor works fine.

**Comment by markwoon** [comment]
PharmCAT doesn't support gvcf files at the moment.  You can watch for progress on this in #79.

Re: #1 
* invalid AD - you can ignore this, it will be handled correctly in the future
* missing several PGx genes - that's unavoidable as you do not provide the data to call them.  You input file only has 14 positions...
