### ISSUE TITLE
Possible bug in PharmCAT version 2.0.3 DPYD implementation

### ISSUE THREAD

**Issue by anh151** [PharmGKB/PharmCAT#120]
PharmCAT version 2.0.3 with preprocessor from the development branch.

This may be me misinterpreting the new method of calling DPYD so correct me if I'm wrong. If input data is unphased, the output for a sample will have no diplotype called unless all variants are homozygous (alt or ref). In a scenario where a sample is heterozygous for at least one variant, the diplotype call should not be assigned. Instead, all alleles/variants that are observed are returned. 

If the above is correct, the following scenario should not be possible.

Consider a sample with the following variants for DPYD
chr1:97515839T>C (hom alt)
chr1:97883329A>G (het).

This is a sample that now has 3 alleles which would be c.1627A>G (*5), c.1627A>G (*5), c.85T>C (*9A). However, I receive a diplotype call for this sample as c.1627A>G (*5)/[c.1627A>G (*5) + c.85T>C (*9A)]. Additionally at the end of the DPYD section within the json match file I find the effectivelyPhased field as True. 

I think this bug might stem from using the "missing-to-ref" argument in the preprocessor which adds the missing variants as phased variants. 

An alternative example that behaves differently is the following:
chr1:97078987G>T (het)
chr1:97515839T>C (het)
chr1:97883329A>G (het)
In this example I don't get a diplotype assigned and instead I get all of the alleles/variants provided within the haplotypeMatches field. Additionally, the effectivelyPhased field is False. This is what I would expect to happen based on the description provided in the PharmCAT documentation. 

-Andrew

**Comment by BinglanLi** [comment]
Hi Andrew, this is not a bug but I do see your point. EffectivelyPhased has nothing to do with the actual phasing status and is used internally in the tool. PharmCAT does not infer phasing status. With regard to the DPYD behavior, we will update the documentation to help a better understanding.

**Comment by markwoon** [comment]
Updated docs available at https://pharmcat.org/methods/Gene-Definition-Exceptions/#calling-dpyd-named-alleles

Hopefully that clears things up.

If not, please reopen the issue.
