### ISSUE TITLE
Wrong recommendation from CPIC for capecitabine and fluorouracil

### ISSUE THREAD

**Issue by krukanna** [PharmGKB/PharmCAT#126]
* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
Exactly the same recommendation for capecitabine and fluorouracil for phenotype Intermediate Metabolizer 

> _Reduce starting dose by 50% followed by titration of dose based on toxicity or therapeutic drug monitoring (if available)._

* **What is the expected behavior?**

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/81685638/215712879-07d033e8-c266-4f2a-a338-611996d6dbb5.png)

Recommendation in CPIC publication for Intermediate Metabolizer are different for different activity score.
Correct recommendation should be:

> _Reduce starting dose by 25% to 50% followed by titration of dose based on toxicity or therapeutic drug monitoring (if available)._

* **Please tell us about your environment:**
  - PharmCAT Version: 2.2.1

**Comment by whaleyr** [comment]
Thanks for finding this, we've found the source of the issue and it will be fixed in the next release.

**Comment by whaleyr** [comment]
This has been fixed in [v2.2.2](https://github.com/PharmGKB/PharmCAT/releases/tag/v2.2.2). Download the new JAR and you should be good to go.

**Comment by mwcarrillo** [comment]
This was actually not an error. The CPIC guideline was updated in November 2018, after the manuscript was released - a reason to consult the CPIC or PharmGKB websites (cpicpgx.org or pharmgkb.org) where updates are posted.  See https://cpicpgx.org/guidelines/guideline-for-fluoropyrimidines-and-dpyd/ for the full explanation of why the PharmCAT data was correct. Therefore, this was rolled back to the updated guidance.
