### ISSUE TITLE
Problem at table formatting in example file

### ISSUE THREAD

**Issue by KraftRicardo** [PharmGKB/PharmCAT#130]
Hello!

* **Do you want to request a *feature* or report a *bug*?**

I found a problem in the formatting I believe.

* **What is the current behavior?**
I used your PharmCAT\docs\examples\pharmcat.example.vcf and applied the current version 2.2.3. The .html output has this weird formatting around here. The rest of the formating seems fine.
![image](https://user-images.githubusercontent.com/34013744/224694476-51a4e148-f2e6-4337-9019-839b07f04213.png)
Then I thought about applying the preprocessor first, but the problematic formatting remains. 

* **What is the expected behavior?**
In comparision this is what your example .html looks like at this place:
![image](https://user-images.githubusercontent.com/34013744/224695567-df98bf45-7803-4423-91c1-9b175263e4f1.png)

I ran this:
* python3 pharmcat_vcf_preprocessor.py -vcf test-input/pharmcat.example.vcf -o test-output
* java -jar pharmcat-2.2.3-all.jar -vcf test-output/pharmcat.example.preprocessed.vcf

* **Please tell us about your environment:**
  
  - PharmCAT Version: 2.2.3
  - JDK Version: [ JDK8 | OpenJDK | etc ] Orcale OpenJDK version 19.0.2
  - Environment: [ Windows | macOS | Linux distro | etc ] Windows 10

**Comment by whaleyr** [comment]
Can confirm, I'm seeing this on the output of the G6PD test cases. Thanks for bringing this up, we'll update the layout to fix.
