### ISSUE TITLE
Inconsistent report names?

### ISSUE THREAD

**Issue by KraftRicardo** [PharmGKB/PharmCAT#131]
* **Do you want to request a *feature* or report a *bug*?**

Bug

* **What is the current behavior?**

When I run PharmCAT 2.2.3 with 
**pharmcat.example.vcf** and **NA12878-TwistWE_v1-220729_A00726_0553_AHH5WMDRX2.hard-filtered.preprocessed.vcf**
I get
**NA12878-TwistWE_v1-220729_A00726_0553_AHH5WMDRX2.hard-filtered.report.html**
and
**pharmcat.example.report.html**

which shows that a part of the original file name, in this case the word ".preprocessed", is omitted in the second example. Is this intended?

* **What is the expected behavior?**

I would expect the naming to be like this:
**NA12878-TwistWE_v1-220729_A00726_0553_AHH5WMDRX2.hard-filtered.preprocessed.report.html**

* **Please tell us about your environment:**
  
  - PharmCAT Version: 2.2.3
  - JDK Version: [ JDK8 | OpenJDK | etc ] openjdk version "17.0.3" 2022-04-19 LTS
  - Environment: [ Windows | macOS | Linux distro | etc ] Windows 10

**Comment by markwoon** [comment]
Yes, this is expected.  `.preprocessed`, `.matcher`, `.phenotype` and `.report` are sub-extensions that we use and we strip them off to determine the base file name.
