### ISSUE TITLE
Discarded position in Pharmcat report

### ISSUE THREAD

**Issue by krukanna** [PharmGKB/PharmCAT#135]
* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**

I have below warning in Pharmcat reports:
_Discarded genotype at this position because REF in VCF (A) does not match expected reference (AGGAGTC)_
It's discarded for all my samples.

Warning in command line from vcf preprocessor:
  _* WARNING: "chr13:48037782 REF=A ALT=C" does not match PharmCAT expectation of ALT at "chr13:48037782 REF=AGGAGTC ALT=A"
  _* WARNING: "chr13:48037782 REF=A ALT=C" does not match PharmCAT expectation of ALT at "chr13:48037782 REF=A ALT=AGGAGTC"__

But in my input vcf file I see that position with correct ref:
`chr13   48037782        .       AGGAGTC CGGAGTC,A`

Here are lines from preprocessed vcf by your preprocessor (other positions are not splitted into two lines, even if they have more alt alleles):
```
chr13	48037782	rs746071566	AGGAGTC	AGGAGTCGGAGTC,A	4892.17	PASS	PX=NUDT15	GT	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	2/0
chr13	48037782	.	A	C	4892.17	PCATxALT	.	GT	0/0	0/0	0/0	0/0	0/0	0/0	0/1	0/1	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/1	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0
```

* **Please tell us about your environment:**
  - PharmCAT Version: 2.3.0

**Comment by BinglanLi** [comment]
Hi, please note that in the PharmCAT report, the discard position refers to the A>C change at Chr13: 48037782, which, as you have shown, is the second line of the preprocess VCF but not a PGx variant. Otherwise, if the INDEL had been discarded instead, PharmCAT would have reported the warning stating that `... REF in VCF (**AGGAGTC**) does not ...`.

**Comment by krukanna** [comment]
Hi, after joint calling all my samples the position looks like:
`chr13   48037782        .       AGGAGTC CGGAGTC,AGGAGTCGGAGTC,A `
Then after normalization (and left-alignment) by your preprocessor:
```
chr13   48037782        .       A       C
chr13   48037782        .       A       AGGAGTC
chr13   48037782        .       AGGAGTC A
```
And in the final preprocessed vcf:
```
chr13   48037782        rs746071566     AGGAGTC AGGAGTCGGAGTC,A 
chr13   48037782        .       A       C      (which is not in pharmcat_positions.vcf)
```
Shouldn't you select only positions with matched alleles (with preprocessor/pharmcat_positions.vcf)?

**Comment by BinglanLi** [comment]
VCF Preprocessor is designed NOT to alter the input VCF. As a result, it retains all PGx allele-defining positions (not only just matching alleles). Please feel free to re-open the issue if you have any further questions.
