### ISSUE TITLE
Issue with pharmcat_vcf_preprocessor.py

### ISSUE THREAD

**Issue by joseMorosoli** [PharmGKB/PharmCAT#136]
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
When I run preprocessor.py on my preferred VCF file, despite indicating that there is a VCF file (-vcf AGDS_VCF/aagds40_grch38.vcf ), I get the following error: Error: no VCF input

This error doesn't appear when I run the program without the flag -refFna

* **If the current behavior is a bug, please provide the steps to reproduce and, if possible, your example input data** via a [Gist](https://gist.github.com) or similar.

pharmcat_vcf_preprocessor.py -vcf AGDS_VCF/aagds40_grch38.vcf -refFna REFERENCE/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz

* **What is the expected behavior?**
I would expect preprocessor.py to use the indicated fai file

* **What is the motivation / use case for changing the behavior?**
I'm analysing data withing a computer cluster and I can't directly download a new FASTA file, therefore I need to indicate where my fai file is.

* **Please tell us about your environment:**
  
  - PharmCAT Version: pharmcat/2.2.2
  - JDK Version: java version "17.0.4.1" 2022-08-18 LTS
  - Environment: CentOS Linux 7 (Core)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)

**Comment by whaleyr** [comment]
According to [the VCF preprocessor docs](https://pharmcat.org/using/VCF-Preprocessor/#advanced-arguments) it seems like your FNA file needs to be uncompressed and indexed (a `.fai` file, not a `.fna.gz` file). Can you try that and report back the results?

**Comment by BinglanLi** [comment]
Could you please clarify what you meant by saying that you expect the VCF Preprocessor to find the **indicated** fai? Let's say a FNA file is named `abc.fna` or `abc.fna.gz`, their corresponding index file should be `abc.fna.fai` or `abc.fna.gz.fai` (as well as an additional abc.fna.gz.gzi by samtools for a compressed file), respectively. The VCF Preprocessor can find these index files given the input reference by `-refFna`.

**Comment by markwoon** [comment]
Closing due to lack of input.
