### ISSUE TITLE
Uniallelic_vcf file generation

### ISSUE THREAD

**Issue by dineshpeace** [PharmGKB/PharmCAT#137]
* **Do you want to request a *feature* or report a *bug*?**

bug

* **What is the current behavior?**
[E::hts_open_format] Failed to open file "/secure/path/preprocessor/pharmcat_positions.uniallelic,vcf.bgz": Permission denied
Can't write to "/secure/path/preprocessor/pharmcat_positions.uniallelic,vcf.bgz": Permission denied

* **If the current behavior is a bug, please provide the steps to reproduce and, if possible, your example input data** via a [Gist](https://gist.github.com) or similar.

I have provided a multisample VCF file that is vcf.gz. Please help to over come this issue.  
Accessing through HPC so can not modify permission on the installation path

* **What is the expected behavior?**
Should not ask for uniallelic file .

* **What is the motivation / use case for changing the behavior?**
-

* **Please tell us about your environment:**
  
  - PharmCAT Version: ??? PharmCAT v1.8.0
  - JDK Version: [ JDK8 | OpenJDK | etc ] java 16.0.1
  - Environment: [ Windows | macOS | Linux distro | etc ] Linux

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)

I saw these file in Docker image, but not in Github. 
Can you provide the files to copy in the location
![Screenshot from 2023-05-02 13-20-38](https://user-images.githubusercontent.com/34877292/235651189-3b717cb1-064b-4bd1-aeef-35d7abe0c8d1.png)

**Comment by BinglanLi** [comment]
Please note that `pharmcat_positions.uniallelic.vcf.bgz` is created by the VCF Preprocessor as an intermediate file based on the `pharmcat_positions.vcf.bgz` to help normalize your input VCF. 

I noticed that there is a comma ',' between `uniallelic` and the file extension `vcf.bgz` in your file name. Please check your command or provide your whole command for us to help diagnose the issue.

**Comment by markwoon** [comment]
1) Based on the error ("Permission denied") - are you sure you are running the script in a directory where you have write permission?  

2) Is this running in Docker?

3) You directory structure says PharmCAT 1.8.0 but the VCF Preprocessor says 2.4.0.  You should really be running the same version of both.

4) More details on exactly what your `starallele.sh` script is doing would be helpful as well.

**Comment by dineshpeace** [comment]
Thanks 
@BinglanLi 
1. The comma is a typo. pharmcat_positions.uniallelic.vcf.bgz is the correct name
2. I dont have write permission on the folder. Can it be written elsewhere or can I load a copy of that file from Docker ?

@markwoon 
1. Yes I dont have write permission in the folder. I am using the tools in HPC where tools installed path is write protected. Can I write this file elsewhere ?
2. I am not using Docker. Its installed from Github.
3. I will try to use the same version for both PharCAT and VCF preprocessor
4. I am passing a multisample VCF file to split into individual samples. Attached the code

Is it possible to overcome the permission issue, by writing the "pharmcat_positions.uniallelic.vcf.bgz" to another location ?

**Comment by BinglanLi** [comment]
The easiest fix is to provide the VCF Preprocessor with a pharmcat_position.vcf.bgz (available in GitHub or release) under a writable folder using `-refVcf`.

**Comment by markwoon** [comment]
I don't see any attached code, but you no longer have to split multisample VCFs if you don't want to.

If you are actually running the latest version of PharmCAT, then I encourage you to check out our documentation at https://pharmcat.org.  If you don't have any special needs, we now have a single script that wraps around both the preprocessor and PharmCAT.  See https://pharmcat.org/using/Running-PharmCAT-Pipeline/ for details.

In the future, I'll include the uniallelic files with the release, but until then, you can do as Binglan suggested, or just copy the file out of Docker.

Whatever you do, please make sure you are using the same version for everything (preprocessor, PharmCAT, data files).

**Comment by markwoon** [comment]
Closing due to lack of input.
