### ISSUE TITLE
Does PharmCAT upload user data somewhere?

### ISSUE THREAD

**Issue by KraftRicardo** [PharmGKB/PharmCAT#138]
Hello everyone,

we will be using PharmCAT with sensitive patience data at our department. I would like to ask whether PharmCAT does upload any of the input data to some external place. As far as I understood the code I did not see such behavior but I need to make sure and hear your answer on this. 

Thank you and have a nice day!

**Comment by whaleyr** [comment]
PharmCAT does not transmit or upload any input data off of the system that it's being run on.
