### ISSUE TITLE
pharmcat_vcf_preprocessor.py

### ISSUE THREAD

**Issue by lingyeah89658** [PharmGKB/PharmCAT#142]
My bcftools version is 1.8, but when I try to run pharmcat_vcf_preprocessor.py, there is something wrong with it.
![微信图片_20230530171649](https://github.com/PharmGKB/PharmCAT/assets/77489545/24e9627b-9294-437c-8cb9-b461db721c2c)
How to solve it?

**Comment by markwoon** [comment]
The clue is right in the output. You need bcftools 1.16 or higher.

1.8 is *not* higher than 1.16.
