### ISSUE TITLE
G6PD - wrong function assignment for Mediterranean, Dallas, Panama, Sassari, Cagliari, Birmingham

### ISSUE THREAD

**Issue by snehaleela** [PharmGKB/PharmCAT#144]
* **Do you want to request a *feature* or report a *bug*?**
* Bug
* Current when provided only with Mediterranean, Dallas, Panama, Sassari, Cagliari, Birmingham allele value for G6PD gene - The output throws the value as unassigned function .
* Need to get CPIC Function Assignment II/Deficient [More info on allele function](https://www.pharmgkb.org/page/cpicFuncPhen)

* **What is the current behavior?**
* Current when provided only with Mediterranean, Dallas, Panama, Sassari, Cagliari, Birmingham allele value for G6PD gene - The output throws the value as unassigned function .

* **If the current behavior is a bug, please provide the steps to reproduce and, if possible, your example input data** via a [Gist](https://gist.github.com) or similar.

* **What is the expected behavior?**
Need to get CPIC Function Assignment II/Deficient

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - PharmCAT Version: 
  - JDK Version: [ JDK8 | OpenJDK | etc ] 
  - Environment: [ Windows | macOS | Linux distro | etc ] Mac 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)

**Comment by mwcarrillo** [comment]
Could you please let us know what version of PharmCAT you are using? It will help us address this issue, thanks.

**Comment by BinglanLi** [comment]
Could you please also share how you ran PharmCAT? How did you `provide only with Mediterranean, Dallas, Panama, Sassari, Cagliari, Birmingham allele value for G6PD`?

**Comment by BinglanLi** [comment]
We tested PharmCAT v2.5.0 using VCFs with hemizygous, heterozygous, and homozygous genotypes of the allele. All the tests returned the correct allele and function. We can't replicate the error. Please use the most recent PharmCAT release for the latest content updates.

We are closing the issue. Please feel free to reopen the issue and provide more information.
