### ISSUE TITLE
Update flowchart

### ISSUE THREAD

**Issue by whaleyr** [PharmGKB/PharmCAT#15]
We need to update [the PharmCAT flowchart](https://github.com/PharmGKB/PharmCAT/blob/master/design/flowchart/PharmCAT-Flowchart.svg).

@markwoon Do you have the source document for this? If you want to do the update yourself I can tell you the changes, otherwise can you share it with me so I can make the updates?

Looking at the metadata it seems this was made in Lucidchart.

**Comment by markwoon** [comment]
Link sent.

**Comment by whaleyr** [comment]
Fixed in https://github.com/PharmGKB/PharmCAT/commit/0c6dab5600bc3999b4ea3e4f3ed8ed79afee2aa4
