### ISSUE TITLE
Parameter for outside calls in pharmcat_pipeline

### ISSUE THREAD

**Issue by MarioCazalla** [PharmGKB/PharmCAT#151]
* **Do you want to request a *feature* or report a *bug*?**

Which is the parameter for add outside calls if I using the pharmcat_pipeline?

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and, if possible, your example input data** via a [Gist](https://gist.github.com) or similar.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - PharmCAT Version: 2.7.0
  - JDK Version: 17
  - Environment: Ubuntu

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)

**Comment by markwoon** [comment]
See the "Outside Calls" section in the docs: https://pharmcat.org/using/Running-PharmCAT-Pipeline/#outside-calls

There is no parameter.  You just name the file correctly and it will be used.
