### ISSUE TITLE
Is it possible to use exemptions.json without building from source?

### ISSUE THREAD

**Issue by hudja** [PharmGKB/PharmCAT#153]
Hello,

I use the latest 2.7.1 version and I cannot find the way to specify exemptions.json. Do I need to build from source for that? I tried, but my `./gradlew test` fails. I found an old issue where json was specified with -na flag, but I cannot find this flag anymore.

Thank you!

**Comment by markwoon** [comment]
You should not need to specify `exemptions.json`.

Can yo uplease provide more details on what you're trying to do?  Are you just checking out the source from GitHub and running `./gradlew test`?  If so, please add the console log to to the issue.

**Comment by hudja** [comment]
I would like to exclude a couple of star alleles from the detection list, but I think I figured it out. I just use `-def` flag and point to the following folder `PharmCAT-2.7.1/src/main/resources/org/pharmgkb/pharmcat/definition/alleles/`. I edited `exemptions.json` inside this folder and it seems working.
