### ISSUE TITLE
Missing CPIC version

### ISSUE THREAD

**Issue by krukanna** [PharmGKB/PharmCAT#157]
* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
In json file in version 2.8.0 and 2.8.1 is missing field for cpicVersion:
```
  "pharmcatVersion": "2.8.1",
  "cpicVersion": null
```
In any previous version for example:
```
  "pharmcatVersion": "2.5.0",
  "cpicVersion": "v1.26.0",
```

* **If the current behavior is a bug, please provide the steps to reproduce and, if possible, your example input data** via a [Gist](https://gist.github.com) or similar.
`java -jar /pharmcat/pharmcat.jar -vcf $vcf -del -reporterJson -o Pharmcat_output`

* **Please tell us about your environment:**
  
  - PharmCAT Version: 2.8.0 and 2.8.1 docker version

**Comment by Bioinf-usr** [comment]
It is missing in version 2.8.2 as well.

**Comment by BinglanLi** [comment]
Thank you for reporting the issue. We are looking into it.

**Comment by whaleyr** [comment]
This will be fixed in the next release.

**Comment by lacek** [comment]
The issue reappears in v2.14.0

```
$ /opt/java/openjdk-17/bin/java -jar /opt/pharmcat/2.13.0/pharmcat.jar -vcf tmp/pharmcat/default.preprocessed.vcf.bgz -s "$SAMPLE" -rt "$SAMPLE" -o tmp/pharmcat -bf 2.13.0 -reporterJson
$ jq -r 'with_entries(select(.key | IN("pharmcatVersion","cpicVersion","dpwgVersion")))' tmp/pharmcat/2.13.0.report.json
{
  "pharmcatVersion": "2.13.0",
  "cpicVersion": "v1.39.0, 2024-05-23-09-04",
  "dpwgVersion": "2024-05-23-09-04"
}

$ /opt/java/openjdk-17/bin/java -jar /opt/pharmcat/2.14.0/pharmcat.jar -vcf tmp/pharmcat/default.preprocessed.vcf.bgz -s "$SAMPLE" -rt "$SAMPLE" -o tmp/pharmcat -bf 2.14.0 -reporterJson
$ q -r 'with_entries(select(.key | IN("pharmcatVersion","cpicVersion","dpwgVersion")))' tmp/pharmcat/2.14.0.report.json
{
  "pharmcatVersion": "2.14.0"
}
```

**Comment by whaleyr** [comment]
PharmCAT data has changed. CPIC and DPWG now both come from the same data source (plus, FDA data is now included) so they no longer have separate versions. There is a new `dataVersion` property which applies to all data in PharmCAT. You can see this in [the example JSON report](https://github.com/PharmGKB/PharmCAT/blob/main/docs/examples/pharmcat.example.report.json)
