### ISSUE TITLE
No CPIC variants found

### ISSUE THREAD

**Issue by Bioinf-usr** [PharmGKB/PharmCAT#158]
Hi,

I am using pharmcat version 2.8.2. In the reported html file, I see that for some of the genes such as CFTR, CACNA1S and RYR1 the inferred genotype is "_No CPIC variants found_ " . May I know what does it mean?

Thank you.

**Comment by whaleyr** [comment]
It means that no variants that CPIC uses for recommendation lookup were found in the sample data provided for those genes.

**Comment by Bioinf-usr** [comment]
Sorry, For example in the case of _CACNA1S_.  The variants recommended according to CPIC are c.3257G>A, c.520C>T and Reference. And in my VCF file, I can find them. Even in the report, they are mentioned in the _"CACNA1S allele match data"_ section. Am I missing something? When I look into my VCF file, for these positions there is a custom filter that I have added instead of "PASS". Could that be the reason?


<img width="1332" alt="Screenshot 2023-10-12 at 18 39 55" src="https://github.com/PharmGKB/PharmCAT/assets/77389502/fd1421ef-1dcf-4e05-987e-d7f8f6d6f272">
