### ISSUE TITLE
Warfarin Workflow Discrepancy

### ISSUE THREAD

**Issue by Shreyaack** [PharmGKB/PharmCAT#164]
Dear Team,

We find a difference in Warfarin Workflow from Pharmcat and CPIC. Request you to confirm which is the right one to use.

1.	From CPIC Reference Document – https://files.cpicpgx.org/data/guideline/publication/warfarin/2017/28198005.pdf
 
![image](https://github.com/PharmGKB/PharmCAT/assets/151372636/b301ca5b-6056-4ef1-b459-212d874a42a9)

2.	Pharmcat Sample report –
 
![image](https://github.com/PharmGKB/PharmCAT/assets/151372636/da375fc7-d7d8-4aa4-8608-88d01040d652)

Kindly clarify the same.

Pharmcat  version 2.5

**Comment by whaleyr** [comment]
Thank you very much for bringing this to our attention!

The diagram has been fixed and published to the URL: 
https://files.cpicpgx.org/images/warfarin/warfarin_recommendation_diagram.png

The diagram is not embedded in the PharmCAT report, it uses an href, so the updated diagram should be visible the next time the report is opened or refreshed.
