### ISSUE TITLE
HLA Data appearing as N/A instead of positive or negative

### ISSUE THREAD

**Issue by Shreyaack** [PharmGKB/PharmCAT#166]
Per CPIC SOP guidelines, the HLA phenotype is expected to be classified as either positive or negative. Nevertheless, our reports indicate that the phenotype is sometimes recorded as n/a (not applicable). Kindly verify the reason behind this occurrence and clarify whether it is an issue. Could you also provide guidance on the anticipated behavior concerning HLA (A and B) classifications?

**Comment by whaleyr** [comment]
The HLA genes may show up as "N/A" phenotype because you have no HLA data in your sample.

There may be other reasons but it's hard to say without seeing specific examples. Can you post a synthetic example of the sample data that you think should be getting an HLA call but isn't?

**Comment by mwcarrillo** [comment]
To add to what Ryan said, CPIC uses terms such as "No HLA-B Result" (e.g. carbamazepine guideline), which would be equivalent to N/A

**Comment by mwcarrillo** [comment]
CPIC does not provide phenotypes for HLA. Please read the CPIC guidelines and supporting files on PharmGKB or the CPIC website for more explanation. I think it will become clear if you read the guidelines.

**Comment by Shreyaack** [comment]
Dear Michelle

Thank you for your response. I did go through the guidelines and understood how HLA is represented as positive or negative. I would like to understand better how PharmCat works with respect to Section 2 of the HTML. For some genes we have the genotype, phenotype and activity score. For HLA we have the genotype and no phenotype in that section as shown in the image in my previous report. Could you please help me understand this so we would modify our design accordingly.

Thanks and Regards
Shreyaa

Sent from Outlook for Android<https://aka.ms/AAb9ysg>


Public

Shreyaa Chandrashekar
Product Manager

E: ***@***.***   M: 0502482799
 [Line.gif]
[banner.png]
[G42-Healthcare.png]    <https://www.instagram.com/g42_healthcare/> <https://www.instagram.com/g42_healthcare/> [Instagram.gif] <https://www.instagram.com/g42_healthcare/>   [LinkedIn.gif] <https://www.linkedin.com/company/g42healthcare/>   [Twitter.gif] <https://twitter.com/G42_Healthcare>  <https://www.youtube.com/channel/UCFrG2j438SNjpwFw4odpEeQ> [Youtube.gif] <https://www.youtube.com/channel/UCFrG2j438SNjpwFw4odpEeQ>


Disclaimer: This message contains information that may be confidential and privileged. Unless you are the intended recipient (or authorized to receive this message for the intended recipient), you may not use, copy, disseminate or disclose to anyone the message or any information contained in the message. If you have received the message in error, please advise the sender by reply e-mail, and delete the message.


Public

________________________________

**Comment by markwoon** [comment]
If you want to understand how recommendations are derived, please consult https://pharmcat.org/methods/Matching-Recommendations/

Specifically, https://pharmcat.org/methods/Matching-Recommendations/#method-4-allele-status-lookup :

> While function and phenotype assignments are common for genes used by PharmCAT, there are some genes where function and phenotype are not assigned. For these genes, the mere presence of particular alleles is what the gene result for lookup is based on.
>
> For example, HLA-B is used in a few guidelines and each guideline can use a different allele for matching recommendations. For example, the CPIC guideline for abacavir looks for the presence of the *57:01 allele but the allopurinol guideline looks for the presence of the *58:01 allele. This means one diplotype given to PharmCAT could result in more than one gene result for HLA-B, one for each allele that is used in recommendation lookup.

**Comment by whaleyr** [comment]
There's a bug in the current version of PharmCAT that is causing phenotype values to not display properly in section 2. We are working on a fix and should have it resolved in the next release. That may be what you're seeing.

**Comment by markwoon** [comment]
@whaleyr HLAs don't have phenotypes...

**Comment by whaleyr** [comment]
@markwoon They don't have phenotypes (in the technical sense), but we do show allele presence in the "phenotype" fields of these reports. This is something we've done on PharmGKB for a long time and it got carried over to PharmCAT since that's how we're accustomed to reporting it. If you want to reconsider this we should bring it up with the curators.
