### ISSUE TITLE
CYP2D6 diplotypes with activity score `≥3.75` are not correctly annotated in CPIC JSON data resource

### ISSUE THREAD

**Issue by kuanyili** [PharmGKB/PharmCAT#171]
More specifically, diplotypes

- `*1x≥3/*41x3`
- `*2x≥3/*41x3`

currently have

- "generesult": "Indeterminate"
- "lookupkey": "n/a"
- "activityScore": "n/a"
- "phenotype": "Indeterminate"

in `src/main/resources/org/pharmgkb/pharmcat/phenotype/cpic/CYP2D6.json`.

But instead they shall have

- "generesult": "Ultrarapid Metabolizer"
- "lookupkey": "≥3.75"
- "activityScore": "≥3.75"
- "phenotype": "Ultrarapid Metabolizer"

according to

- [CYP2D6 Phenotype Table](https://files.cpicpgx.org/data/report/current/gene_phenotype/CYP2D6_phenotypes.xlsx)
- [CYP2D6 Diplotype-Phenotype Table](https://files.cpicpgx.org/data/report/current/diplotype_phenotype/CYP2D6_Diplotype_Phenotype_Table.xlsx)
- CPIC API
    - `curl --silent 'https://api.cpicpgx.org/v1/diplotype?genesymbol=eq.CYP2D6&diplotype=eq.*1x≥3/*41x3'`
    - `curl --silent 'https://api.cpicpgx.org/v1/diplotype?genesymbol=eq.CYP2D6&diplotype=eq.*2x≥3/*41x3'`

Activity score `≥3.75` is also consequently missing in `docs/Phenotypes-List.md`.

Is the JSON data resource generated by a program so I should start from there to ensure future correctness? Or is the file maintained manually so I can just submit a PR by directly editing the file?

**Comment by whaleyr** [comment]
Thanks for letting us know. The data will be updated in the next release.

**Comment by markwoon** [comment]
What you get via the API is real time.

Whenever we release we update the data as well, so what you're seeing now is a snapshot of what was available at release.

**Comment by kuanyili** [comment]
> What you get via the API is real time.
> 
> Whenever we release we update the data as well, so what you're seeing now is a snapshot of what was available at release.

This was also what I thought, but I checked `cpic_db_dump-v1.35.0.sql.gz`, which was released on Dec. 19, 2023. The `≥3.75` annotation was there, and the JSON stated that it uses CPIC version v1.35. Am I missing something?

**Comment by whaleyr** [comment]
@markwoon There was a mismatch between DB's that caused what's in the CPIC DB to not match what was pulled in DataManager. We can talk specifics later, but I will fix this immediate problem in the next release.

**Comment by whaleyr** [comment]
The fix has been pushed into development branch and will be in the next release.

**Comment by kuanyili** [comment]
Thank you for the support! 😄

**Comment by kuanyili** [comment]
@whaleyr @markwoon Hi! This issue kind of resurfaced since commit a57b955b3f42e0786154093a437e74393f89b4c0. Any idea?

**Comment by whaleyr** [comment]
Looking into it, thanks for pointing it out.

We changed how we handle diplotype data so must have re-introduced a bug.

**Comment by whaleyr** [comment]
Found the problem and pushed an updated phenotype file in cae0f8c6da998b0abc5ca2fc78aa7fa69767d600 that should address this issue.

**Comment by kuanyili** [comment]
Cool! Many thanks!
