### ISSUE TITLE
Missing genotypes-drugs data in JSON report

### ISSUE THREAD

**Issue by atfrase** [PharmGKB/PharmCAT#18]
In the JSON report, the .genotypes[].drugs[] structure doesn't seem to be written correctly to the file. For example, we see:

```json
{
  "totalGenes": 9,
  "generatedOn": "August 02, 2018",
  "geneCalls": [
...
  ],
  "calledGenes": 9,
  "genotypes": [
    {
      "phenotype": [
        "N/A"
      ],
      "called": true,
      "functions": [
        "N/A"
      ],
      "gene": "CFTR",
      "drugs": [
        {}
      ],
      "calls": [
        "No CPIC variants found"
      ],
      "missingVariants": "Yes",
      "astrolabe": false,
      "hasMessages": false
    },
    {
      "phenotype": [
        "Intermediate Metabolizer"
      ],
      "called": true,
      "functions": [
        "One normal function allele and one no function allele"
      ],
      "gene": "CYP2C19",
      "drugs": [
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {}
      ],
      "calls": [
        "*1/*2"
      ],
      "missingVariants": "Yes",
      "astrolabe": false,
      "hasMessages": false
    },
    {
      "phenotype": [
        "Normal Metabolizer"
      ],
      "called": true,
      "functions": [
        "Two normal function alleles"
      ],
      "gene": "CYP2C9",
      "drugs": [
        {},
        {}
      ],
      "calls": [
        "*1/*1"
      ],
      "missingVariants": "Yes",
      "astrolabe": false,
      "hasMessages": false
    },
...
```

So each .genotypes[] object has a .drugs[] array with a different number of entries, as if it were trying to report a different number of drugs for each, but the actual entries in the .drugs[] list are all just empty objects rather than strings or however they're meant to be reported.

**Comment by muhligs** [comment]
Hi, 
I use pharmCAT v2.2.3
I am also looking for this info in the match.json and phenotype.json, but all I find is
`"relatedDrugs": [],`
in the phenotype.json file, and nothing in the match.json file. 
this vector is empty for alle genes in all samples. 

Can you help me to understand where to find this information?

Thanks, 
Morten

**Comment by BinglanLi** [comment]
Have you produced and checked the reporter JSON?

**Comment by markwoon** [comment]
`relatedDrugs` only gets filled in by the reporter.

If you want to produce JSON, you'll need to provide the `-reporterJson` flag.

Please open a new issue if you have further questions.

**Comment by muhligs** [comment]
Sounds like the way to go. Thanks both.
