### ISSUE TITLE
ExecutionException due to UnexpectedStateException: Multiple Phenotypes for Gene CYP2C9

### ISSUE THREAD

**Issue by ngslabex** [PharmGKB/PharmCAT#180]
I have faced with this error:
Where could I go wrong?
Thanks.
![image](https://github.com/PharmGKB/PharmCAT/assets/44006041/30e4d39e-abb6-4cd3-8362-cb286b3ba454)

**Comment by BinglanLi** [comment]
Hi @ngslabex, thank you for sharing the issue with us. 

Could you please share a mock VCF (removing the personal identifiable information)? It will help us replicate the error and resolve the issue.

**Comment by ngslabex** [comment]
Thank you very much for your quick response and interest. @BinglanLi 

I share it immediately.

https://drive.google.com/file/d/1s_jkmkmIdi1WILyrzp-69O5nZn1SJLPB/view?usp=sharing

**Comment by markwoon** [comment]
@ngslabex Could you please provide the command line you're using to run PharmCAT?  What options are you providing?

**Comment by ngslabex** [comment]
> @ngslabex Could you please provide the command line you're using to run PharmCAT? What options are you providing?

I have used prompt that: @markwoon 


```
docker run --rm  \
	-v /home/user/Desktop:/pharmcat/data \
	pgkb/pharmcat ./pharmcat_pipeline \
	data/sample.vcf.bgz \
	-v --reporter-extended
```

**Comment by markwoon** [comment]
We understand the problem and have a fix in place.  Hope to release a new version next week.

**Comment by whaleyr** [comment]
@ngslabex The new release has the fix for your problem. Please download [v2.12.0](https://github.com/PharmGKB/PharmCAT/releases/tag/v2.12.0)

**Comment by lacek** [comment]
The issue occurs again in v2.13.0.

I am able to reproduce issue with sample.vcf.bgz in https://github.com/PharmGKB/PharmCAT/issues/180#issuecomment-2040575437 with below command:

```bash
./pharmcat_vcf_preprocessor.py -refFna /mnt/data/ref/Homo_sapiens_assembly38.fasta -s EO_EO --vcf sample.vcf.bgz -o . -bf test
java -jar pharmcat.jar -vcf test.preprocessed.vcf.bgz -s EO_EO -rt EO_EO -o . -bf test -reporterJson
```

The same commands works with v2.12.0

**Comment by whaleyr** [comment]
Found the problem. It was related to the new FDA content. I have a fix for this on the development branch and it will be included in the next release.

**Comment by lacek** [comment]
Thank you @whaleyr !

Do you have an ETA for the next release?

**Comment by whaleyr** [comment]
"Soon"

We have a couple other data updates coming through from PharmVar and CPIC. Once those have landed we'll cut the release, within the next week or two, I assume.
