### ISSUE TITLE
Support for CPIC level C drugs

### ISSUE THREAD

**Issue by Bioinf-usr** [PharmGKB/PharmCAT#185]
Hi, 

Just wondering if there is a way to report CPIC level C drugs as well in the reporting? Currently they are restricted to level A or B I think.

Please let me know if I am missing anything.

Thank you.

**Comment by mwcarrillo** [comment]
CPIC level C drugs are those with no prescribing recommendations based on genetics (see https://cpicpgx.org/prioritization/#cpicLevels).
