### ISSUE TITLE
PMID null in Pharmcat json report

### ISSUE THREAD

**Issue by soniafont** [PharmGKB/PharmCAT#187]
* **Do you want to request a *feature* or report a *bug*?**
Bug report

* **What is the current behavior?**
pmid value is 'null' for all entries in pharmcat json report (Pharmcat Version 2.13.0)

* **What is the expected behavior?**
pmid value should be the pubmed id for a certain citation. This used to work in previous pharmcat versions (last version tested was 2.8.3, it worked in that version)

* **What is the motivation / use case for changing the behavior?**
pmid is needed for report

* **Please tell us about your environment:**
  - PharmCAT Version: 2.13.0
  - JDK Version: openjdk=17.0.3
  - Environment: linux

**Comment by whaleyr** [comment]
This will be fixed in the next release (which should be very soon).
