### ISSUE TITLE
Dead link in PharmGKB footnote for FDA label

### ISSUE THREAD

**Issue by lacek** [PharmGKB/PharmCAT#194]
The URL https://www.pharmgkb.org/fda in footnote for FDA label is an invalid link, redirecting to a page of "Resource Not Found":
https://github.com/PharmGKB/PharmCAT/blob/89262600f81dc827331d25a739a1a7391d75dea6/src/main/resources/org/pharmgkb/pharmcat/reporter/report.hbs#L345

**Comment by whaleyr** [comment]
This will be addressed on the PharmGKB side soon. In the mean time you can access https://www.pharmgkb.org/page/fda

**Comment by whaleyr** [comment]
The page at the URL https://www.pharmgkb.org/fda has been implemented so this is no longer an issue.
