### ISSUE TITLE
gVCF checking is too loose and misrecognize VCF as gVCF

### ISSUE THREAD

**Issue by lacek** [PharmGKB/PharmCAT#199]
For VCF with annotations, the INFO field may contain annotation tag (e.g. ANN/CSQ), in which gene names are included, e.g.:

```vcf
chr1	48722964	.	G	C	43.21	PASS	P;ANN=C|downstream_gene_variant|MODIFIER|BEND5|BEND5|transcript|NM_024603.4|protein_coding||c.*4922C>G|||||4555|	T:GQ:DP:AD:AF:PS       0|1:2:9:5,2:0.2222:10019
```

When it hits lines with gene symbol that contains the string `END`, it considers it as a gVCF.

In my case, workaround using the optional `--no-gvcf-check`, or removing the ANN field before feeding into PharmCAT script are fine.
However, I guess more rigid checking can be adopted instead, e.g. checking on the VCF header to determine if the INFO field END is defined.

**Comment by BinglanLi** [comment]
Hi @lacek, thank you for reporting the issue. The preprocessor now checks the exact block length annotated by the `END` field. This prevents the preprocessor from confusing a reference block with an accidental gene name as in your case, or with a variant length annotation from other tools. We appreciate the feedback. Please feel free to let us know if you have any questions in the future.
