### ISSUE TITLE
 -phenotyper -po sample.tsv problem

### ISSUE THREAD

**Issue by Ahmadhajeer89** [PharmGKB/PharmCAT#202]
*** **What is the current behavior?****

I am facing this error when I am trying to use outside calls, using the sample file from PharmCAT website, as the following:

```
java -jar pharmcat-2.15.5-all.jar -phenotyper -po sample.tsv
java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.resolve(String)" because "this.m_baseDir" is null
	at org.pharmgkb.pharmcat.Pipeline.<init>(Pipeline.java:131)
	at org.pharmgkb.pharmcat.PharmCAT.main(PharmCAT.java:197)
```

Note that using the -VCF works well without problems.

  
  - PharmCAT Version:
  pharmcat-2.15.5-all.jar

  - JDK Version: [ JDK8 | OpenJDK | etc ]:
openjdk 21.0.5 2024-10-15 LTS
OpenJDK Runtime Environment Temurin-21.0.5+11 (build 21.0.5+11-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.5+11 (build 21.0.5+11-LTS, mixed mode)

  - Environment: [macOS, Monterery ]

**Comment by markwoon** [comment]
Apologies for the delay in responding. Can you try providing the full path to the `sample.tsv` file?

**Comment by markwoon** [comment]
> so the sample has an un-documented variant?

Looks like it.

See https://pharmcat.org/methods/NamedAlleleMatcher-201/#undocumented-variations for details
