### ISSUE TITLE
Software versioning for breaking change

### ISSUE THREAD

**Issue by lacek** [PharmGKB/PharmCAT#203]
I updated from v2.14.0 to v2.15.5 and found my script failed because of the change in v2.15.5 (commit 98f7559), in which the `--missing-to-ref` is replaced by 2 other finer options.

Removing a CLI option is a breaking change. To stick to Semantic Versioning as mentioned in the [documentation](https://github.com/PharmGKB/PharmCAT/blob/v2.15.5/docs/Versioning.md#versioning), I guess it better to either:
- version as v2.X.Y but keep the option `--missing-to-ref` (with deprecation message)
- or version as v3.X.Y with the option `--missing-to-ref` removed

Thank you for actively maintaining PharmCAT anyway.

**Comment by markwoon** [comment]
I'm not a fan of software that doesn't follow semver either, which is why that flag was put back in commit fad76c9776411a6bb735c910f8d5ab8d94a4ebd0 to avoid the breaking change.

If this is failing for you, it's a separate issue.

How are you using the software?  Direct download?  Via docker?

**Comment by lacek** [comment]
Thanks for the clarification. I mistaken the error message and it's actually an issue of my own usage.
