### ISSUE TITLE
Java error reported when testing against 1000 Genomes VCF

### ISSUE THREAD

**Issue by rhdolin** [PharmGKB/PharmCAT#22]
* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**
For this VCF row (from 1000 Genomes VCF): 'chr6	18128428	.	T	A	.	.	NS=1;AN=2;AC=2;CGA_XR=dbsnp.52|rs7886;CGA_FI=7172|NM_000367.2|TPMT|UTR3|UNKNOWN-INC	GT:PS:FT:GQ:HQ:EHQ:CGA_CEHQ:GL:CGA_CEGL:DP:AD:CGA_RDP	1/1:.:PASS:115:891,115:891,115:49,52:-891,-115,0:-52,-49,0:54:54,54:0'

I get this Java error: 'Error parsing VCF data line'

* **If the current behavior is a bug, please provide the steps to reproduce and, if possible, your example input data** via a [Gist](https://gist.github.com) or similar.
Uploaded 'HG00655.b38.rev.vcf.txt'

* **What is the expected behavior?**
Valid VCF files should parse

* **What is the motivation / use case for changing the behavior?**
Would prefer to not have to manipulate VCFs in order to submit them to PharmCAT. 

* **Please tell us about your environment:**
  
  - PharmCAT Version: 0.6.0
  - JDK Version: java version "1.8.0_161"
  - Environment: Windows

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
Thanks!
[HG00655.b38.rev.vcf.txt](https://github.com/PharmGKB/PharmCAT/files/3045437/HG00655.b38.rev.vcf.txt)

**Comment by markwoon** [comment]
Should be fixed now.
