### ISSUE TITLE
rs12777823 always appears as missing

### ISSUE THREAD

**Issue by rtobes** [PharmGKB/PharmCAT#31]
* **Do you want to request a *feature* or report a *bug*?**
A bug

* **What is the current behavior?**
* **If the current behavior is a bug, please provide the steps to reproduce and, if possible, your example input data** via a [Gist](https://gist.github.com) or similar.

rs12777823 always appears as missing, in all our tests and even using your Template that includes that position:
chr10	94645745	rs12777823	G	A	.	PASS	assume-default	GT	0/1

Your Template was downloaded from:
https://raw.githubusercontent.com/wiki/PharmGKB/PharmCAT/pharmcat.example.vcf 

* **Please tell us about your environment:**
  
  - PharmCAT Version: pharmcat-0.7.0
  - Environment: macOS

**Comment by whaleyr** [comment]
Thanks for finding this. I just pushed a fix to our `development` branch. I also updated our example report but it's not reflected on the site yet. You can view it on [the development branch](https://github.com/PharmGKB/PharmCAT/tree/development/docs/examples) though. It will be in the next release.
