### ISSUE TITLE
Erroneous Ref allele in the 

### ISSUE THREAD

**Issue by BinglanLi** [PharmGKB/PharmCAT#35]
* **Do you want to request a *feature* or report a *bug*?**
report a bug

* **What is the current behavior?**
The following line is incorrect in the file `https://github.com/PharmGKB/PharmCAT/releases/download/v0.7.1/pharmcat.v0.7.1.vcf.gz` provided as one of the PharmCAT v0.7.1 release assets.
```chr1    97740414        rs72549309      AAGTA   A       .       PASS    PX=DPYD:Reference[10]isAGTA,DPYD:c.295_298delTCAT[1]isdelAGTA;  GT      0/0```

* **If the current behavior is a bug, please provide the steps to reproduce and, if possible, your example input data** via a [Gist](https://gist.github.com) or similar.
Reference: https://www.ncbi.nlm.nih.gov/snp/rs72549309

* **What is the expected behavior?**
```chr1    97740414        rs72549309      AATGA   A       .       PASS    PX=DPYD:Reference[10]isAGTA,DPYD:c.295_298delTCAT[1]isdelAGTA;  GT      0/0```

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - PharmCAT Version: v0.7.1
  - JDK Version: [ JDK8 | OpenJDK | etc ]
  - Environment: [ Windows | macOS | Linux distro | etc ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by whaleyr** [comment]
@BinglanLi Is this only happening for this deletion in DPYD or does it also happen for other deletions like 3531_3540delAGAAATGGAA in CYP2C9?

**Comment by BinglanLi** [comment]
I didn't see any issue with 3531_3540delAGAAATGGAA in CYP2C9 in the VCF file. There was no tandem repeat or similar sequence via a visual inspection of 100bp flanking region of that indel on UCSC. 

rs72549309 is the only one:
- Current entry in the VCF:  chr1    97740414        rs72549309      AATGA   A
- Record on the dbSNP: https://www.ncbi.nlm.nih.gov/snp/rs72549309
- Anticipated correct entry:  chr1    97740410        rs72549309      GATGA   G
- Reason: Not left-aligned; 2nd copy of a tandem repeat was reported
- (GitHub development branch) correct in src/main/resources/org/pharmgkb/pharmcat/definition/alleles/DPYD_translation.json

However, just as future reference, I indeed found several additional incorrect indels entries in the VCF. But it's not worth reporting them in details as they are not allele defining positions after switching to CPIC. These include: 
- rs121908745 - CFTR
- rs199826652 - CFTR - merged into rs113993960
- rs113993960 - CFTR
- rs121908746 - CFTR
- rs121908747 - CFTR - merged into rs78984783
All of them are off on genomic positions. They are not either left-aligned for a single-nucleotide repeats (SNRs) or a 2nd copy of a tandem repeat is reported.

**Comment by whaleyr** [comment]
Pushed another change for the `ExtractPositions` class. I re-checked all the RSIDs mentioned in this issue and none of them are in the allele definitions anymore so they are no longer showing in the extracted pharmcat.vcf file. I'm going to close this issue since it's a moot point but if there's problems with positions or alleles in the data generated by the new `ExtractPositions` class please make a new issue.
