### ISSUE TITLE
Handle "Allele Status" genes in the Reporter

### ISSUE THREAD

**Issue by whaleyr** [PharmGKB/PharmCAT#38]
The reporter needs to be able to handle "Allele Status" genes when assigning recommendations in the reporter.

The two allele status genes at the moment are: HLA-A and HLA-B. They will rely on outside callers so they won't get any input from the NamedAlleleMatcher. We will also need to explicitly define the format for the outside calls since they won't follow the normal *1/*2 dipltoype format.

More to come...

**Comment by markwoon** [comment]
HLA's are now supported in 2.0.
