### ISSUE TITLE
VCFParser raised an error for VCFs with more than GT format fields

### ISSUE THREAD

**Issue by BinglanLi** [PharmGKB/PharmCAT#45]
* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
PharmCAT VcfParser reported an error for VCF records with more than GT format fields.
`java.lang.IllegalArgumentException: Error parsing VCF data line #543: chr1	97078987	rs114096998	G	A,T	1163	PASS	.	GT:DP:MIN_DP:GQ:PL:PQ:PS:AD:VAF	0|0:.:.:.:.:.:.:.:.,.`

* **What is the expected behavior?**
I thought that PharmCAT VcfParser will ignore fields following the GT.  

* **What is the motivation / use case for changing the behavior?**
I will need to add a feature in the VCF preprocess tools to retain only the GT field if this is what's expected by the VcfParser. 

* **Please tell us about your environment:**
  
  - PharmCAT Version: development
  - JDK Version: java/1.8.0_131
  - Environment: linux

**Comment by whaleyr** [comment]
I believe this is the same issue as #22. It's actually a bug in a dependency and we should have a fix for it soon.

**Comment by BinglanLi** [comment]
They are indeed the same. I am closing this issue so that it's not redundant.

**Comment by markwoon** [comment]
The latest commit should have fix it.
