### ISSUE TITLE
confused by  rs4124874 and rs12777823 variants

### ISSUE THREAD

**Issue by mathob** [PharmGKB/PharmCAT#47]
* **Do you want to request a *feature* or report a *bug*?**

bug

* **What is the current behavior?**

pharmcat_positions_0.8.0.fixed.vcf includes two deletion variants whose representation seems contrary to what is spefified for Deletions on the "VCF Requirements" page

* **If the current behavior is a bug, please provide the steps to reproduce and, if possible, your example input data** via a [Gist](https://gist.github.com) or similar.

java -cp pharmcat-0.8.0-all.jar org.pharmgkb.pharmcat.definition.ExtractPositions -o pgx.vcf
cat pgx.vcf | grep -e rs4124874 -e rs12777823
chr2	233757013	rs4124874	T	.	.	PASS	PX=UGT1A1:*1[5]isT	GT	0/0
chr10	94645745	rs12777823	G	.	.	PASS	POI	GT	0/0

* **What is the expected behavior?**

variants representation with ALT allele not a dot ??

* **What is the motivation / use case for changing the behavior?**

testing PharmCat and wishing to understand messages warning of "missing" variants

* **Please tell us about your environment:**
  
  - PharmCAT Version: 0.8.0
  - JDK Version: java version "1.8.0_221"
  - Environment: macOS 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by mathob** [comment]
forget this please - sorry to bother you

**Comment by whaleyr** [comment]
No worries, this is actually a good question.

You may have already seen but  rs4124874 has recenlty been removed from the UGT1A1 translation on the development branch so it won't be a position reported in future versions.

rs12777823 is what we consider an "extra" position. It's not actually used when matching defined haplotypes but it is a position that curators feel should be included when reporting genotypes. Since it's not used in a haplotype definition we don't have an "ALT" that we expect for that position, and that's what we use to determine what goes in the ALT for that file.

I hope that clarifies things a bit.

**Comment by mathob** [comment]
Yes, that all makes sense - thanks for taking thetime to reply, Ryan.

On 23 Apr 2021, at 3:47 am, Ryan Whaley ***@***.******@***.***>> wrote:


No worries, this is actually a good question.

You may have already seen but rs4124874 has recenlty been removed from the UGT1A1 translation on the development branch so it won't be a position reported in future versions.

rs12777823 is what we consider an "extra" position. It's not actually used when matching defined haplotypes but it is a position that curators feel should be included when reporting genotypes. Since it's not used in a haplotype definition we don't have an "ALT" that we expect for that position, and that's what we use to determine what goes in the ALT for that file.

I hope that clarifies things a bit.

NOTICE
Please consider the environment before printing this email. This message and any attachments are intended for the addressee named and may contain legally privileged/confidential/copyright information. If you are not the intended recipient, you should not read, use, disclose, copy or distribute this communication. If you have received this message in error please notify us at once by return email and then delete both messages. We accept no liability for the distribution of viruses or similar in electronic communications. This notice should not be removed.
