### ISSUE TITLE
how process data imputed to determinate the haplotype?

### ISSUE THREAD

**Issue by Philips-omica-io** [PharmGKB/PharmCAT#48]
hello, i have a data imputed with this format:

#CHROM POS ID REF  ALT  R1 R2 R3
chr22  17739556   rs138753218   C   T   0          0.012   0.988
chr22  17739584   rs4819464       G   A   0.988   0.012   0
chr22  17739720   rs141302967   G   A   0.985   0.015   0
chr22  17739791   rs181391         G   A   0.97     0.03     0
chr22  17739801   rs8190330       G   A   0.926   0.074   0
chr22  17739855   rs117277763   C   T   0.833   0.165   0.02
chr22  17739857   rs8190329       T   C   0.97     0.03     0

R1 specifies the probability that both alleles of the individual correspond to the reference allele

R2 specifies the probability that a single allele of the two corresponds to the mutated allele

R3 specifies the probability that both alleles correspond to the mutated

How could I process this data to run pharmcat and generate the pharmacogenomics report properly?

**Comment by markwoon** [comment]
You have to comply with the VCF format.

Unfortunately, that's not something we can help you with.

**Comment by Philips-omica-io** [comment]
I know, but is there a way to determine the haplotypes with the data I have? specifically with the odds

**Comment by mwcarrillo** [comment]
PharmCAT cannot factor odds into haplotype determination. It simply detects which variants exist in the VCF file and matches them to allele definitions.  You can use the ref/alt data in your file but PharmCAT cannot consider the information in columns R1, R2 and R3.  Or, you can determine which alt/ref calls you have confidence in (based on whatever odds information you have) and then run those in PharmCAT.
