### ISSUE TITLE
Missing calls

### ISSUE THREAD

**Issue by krukanna** [PharmGKB/PharmCAT#57]
* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
![image](https://user-images.githubusercontent.com/81685638/130964389-fd61fc5a-36ba-408b-b2a0-61d6fc02d0a7.png)
I've got missing calls in report. Positions are sequenced and current in vcf , but they are later removed in preprocessing. Some of them are even not present in _pharmcat_positions_0.8.0.vcf.gz_ (for example 
![image](https://user-images.githubusercontent.com/81685638/130965205-433c6f5a-8605-4b03-8c52-cba6be4b33d6.png)
).

* **If the current behavior is a bug, please provide the steps to reproduce and, if possible, your example input data** via a [Gist](https://gist.github.com) or similar.
I sort vcf, remove all INFO fields and all FORMAT fields except for GT and filter to only PASS variants
My code to preprocess:
`python PharmCAT-0.8.0/src/scripts/PharmCAT_VCF_Preprocess.py --input_vcf cohort.genotyped.all.sort.removed.filtered.vcf.gz --ref_seq Homo_sapiens_assembly38.fasta --ref_pgx_vcf pharmcat_positions_0.8.0.vcf.gz --output_folder Pharmcat_preprocess/`

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - PharmCAT Version: 0.8.0
  - JDK Version: [ JDK8 | OpenJDK | etc ]
  - Environment: Linux distro

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by krukanna** [comment]
@whaleyr You understood it correct. Those positions (for example chr1:97450067, chr10:94942213, chr10:94949283, chr13:48037796, chr13:48040982, chr19:38499646) are missing in `pharmcat_positions_0.8.0.vcf` as well as in `pharmcat_positions_0.8.0_updated_06222021.vcf`. As a consequence, I see missing calls in a single sample report (no matter if I got this positions in my vcf or not) 

@BinglanLi 
Ad 1. I run the following command - the output didn't change, still got the same missing calls
`python PharmCAT_VCF_Preprocess.py --input_vcf cohort.genotyped.all.sort.removed.filtered.vcf.gz --ref_seq Homo_sapiens_assembly38.fasta --ref_pgx_vcf pharmcat_positions_0.8.0_updated_06222021.vcf.gz --output_folder Pharmcat/`
Ad 2. Nothing changed, because fasta file is used only to normalization, my problem is when filter vcf to positions from `pharmcat_positions_0.8.0.vcf`
Ad 3. I tested the preprocessing scripts from the development branch, there are indeed some nice fixes, but I suspect that my problem is related to a different issue. I see missing calls in report in position, which are absent in `pharmcat_positions_0.8.0.vcf`. Please answer if maybe a new version of the jar file will solve this problem.

**Comment by BinglanLi** [comment]
Hi @krukanna, thank you for the detailed listing of positions and your patience. The latest release of PharmCAT v1.0.0 should take care of the issue related to this case of missing calls that you see. 

I have tested using a mock file that contains all the PGx positions, including positions for rs72549303, rs1304490498, rs9332131, rs746071566, rs1457579126, and rs121918596 that correspond to your listing of missing calls. All the positions in the mock file was set to alternative alleles; and went through preprocessing and PharmCAT. All the positions were present in the final report html. 

I'm closing the issue but feel free to re-open by leaving a comment if you still run into the same issue.
