### ISSUE TITLE
VCF Preprocessor INDELS

### ISSUE THREAD

**Issue by pmbock1** [PharmGKB/PharmCAT#63]
* **Do you want to request a *feature* or report a *bug*?**
I have a technical question regarding the VCF preprocessor. 

* **What is the current behavior?**
I am utilizing the recommended reference VCF on the preprocessor wiki page (pharmcat_positions_0.8.0_updated_06222021.vcf from the development branch) to run the PharmCAT_VCF_Preprocess.py script and associative scripts which are also from the development branch (not the latest version, but an updated one compared to main).  I hoped to utilize the preprocessor to fix INDELS, but most if not all INDEL positions are still reported by PharmCat as "missing". Investigating some positions show that the original VCF contains the positions of interest and the VCF preprocessor does reformat the position according to the reference VCF correctly. However, PharmCat is still unable to properly find these positions and reports them as "missing" on the HTML report. 

Here is an example. For rs9332131 the reference VCF has the format of:
"chr10	94949281	rs9332131	GA	G	.	PASS	PX=CYP2C9:*1[67]isA,CYP2C9:*6[1]isdelA	GT	./."
My preprocessed VCF, which is run through PharmCat, is formatted accordingly with:
"chr10	94949281	rs9332131	GA	G	283.236	PASS	PX=CYP2C9:*1[67]isA,CYP2C9:*6[1]isdelA;AN=2;AC=0	GT	0/0"

However, the HTML output (shown below) still reports rs9332131 as missing with two main differences. The position is off by 2 and the reference allele is different.

<img width="1440" alt="Screen Shot 2021-09-17 at 3 52 52 PM" src="https://user-images.githubusercontent.com/71155206/133861608-7796cc8b-74d6-412b-9a75-4ac1b20ec149.png">

Is this an issue with PharmCat, the preprocessor, or something on my end? Am I supposed to normalize or adjust the reference VCF in any way? Or is it something different entirely? Any help or clarification would be greatly appreciated.

* **If the current behavior is a bug, please provide the steps to reproduce and, if possible, your example input data** via a [Gist](https://gist.github.com) or similar.

My script to run Pharm at basically does this. A VCF file is created from a CRAM file using bcftools and then preprocessed by the preprocessor script before being run through astrolabe and PharmCat. Reference Genome is the same as the wiki recommends. Let me know if you need any more details. 

* **Please tell us about your environment:**
  
  - PharmCAT Version: 0.8.0
  - JDK Version:  OpenJDK 8 
  - Environment:  Linux distro 

Thank you!!!

**Comment by BinglanLi** [comment]
Hi @pmbock1 this issue should be fixed in the PharmCAT v1.0, which is about to be released soon. Please stay tuned. We will keep you posted.

**Comment by pmbock1** [comment]
Awesome! Thank you for the response @BinglanLi .

**Comment by BinglanLi** [comment]
@pmbock1 Thank you for the patience. PharmCAT v1.0.0 is released earlier this week and have resolved this issue after data update. I validated the output by testing on the UK Biobank data. I am closing this issue, but feel free to re-open it by leaving a comment if you find any related issues.
