### ISSUE TITLE
 Extract pgx regions from input vcf - preprocessing

### ISSUE THREAD

**Issue by krukanna** [PharmGKB/PharmCAT#77]
* **Do you want to request a *feature* or report a *bug*?**
*bug*

* **What is the current behavior?**
In case no sample has a variant in a given position, my input file looks like this (ALT and FILTER are empty, every GT is 0/0 with good quality):
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample1	sample2	sample3
chr1    97078987        .       G       .       121.05  .       .       GT      0/0     0/0     0/0
```

This causes all similar positions to be marked as missing in report (`bcftools isec -c none` in your preprocessing script) - this is a mistake because all samples are hom ref.

* **Please tell us about your environment:**
  
  - PharmCAT Version: 1.2.1
  - JDK Version: [ OpenJDK 17 ]
  - Environment: [Linux distro ]

**Comment by BinglanLi** [comment]
This should be fixed now at the development branch. The change will be included in the next PharmCAT release. I'm closing the issue for now. Please feel free to re-open it if you have any questions.
