### ISSUE TITLE
Improving Preprocessor's support for phased data

### ISSUE THREAD

**Issue by BinglanLi** [PharmGKB/PharmCAT#78]
* **Do you want to request a *feature* or report a *bug*?**

*feature*

* **What is the current behavior?**

Preprocessor relies on bcftools to handle phased data. However, when adding missing positions back to the VCF, bcftools only does it in a way as if the input VCF were only unphased.

* **What is the expected behavior?**

Preprocessor should allow users to define if their VCF is phased and unphased; and handle the VCF accordingly.

* **What is the motivation / use case for changing the behavior?**

Improving Preprocessor's handling of phased data.

**Comment by cariaso** [comment]
shouldn't the presence of phasing be determined by the delimiter of the GT field, so that

A/C is phased
and
A|C is phased

instead of via a command line switch?

**Comment by BinglanLi** [comment]
I'll work on the improvement that scans VCF and automatically determines the phasing status of input VCF.
