### ISSUE TITLE
How to use this tool?

### ISSUE THREAD

**Issue by gpcr** [PharmGKB/PharmCAT#8]
How to use this tool on VCF data ? 
any help ?

**Comment by markwoon** [comment]
PharmCAT is not quite ready for public consumption yet.

We're close, and we'll have documentation when we're done, but we're not there yet.

You're more than welcome to take a look at the code though.  `Haplotyper` would be the main entry point for haplotype calling.

**Comment by gpcr** [comment]
Thanks, just playing with haplotyper:  Can we use it for Grch37 version?

**Comment by markwoon** [comment]
In theory, yes.  But right now the haplotype mapping is in GRCh38.  You'll either have to convert the VCF or the mapping to match.

**Comment by gpcr** [comment]
converting [generatedDefinitions ](https://github.com/PharmGKB/cpic-data/tree/master/generatedDefinitions)to b37 would be easier i believe...any other file need to be changed?

**Comment by markwoon** [comment]
Those are it.

**Comment by gpcr** [comment]
Are b37 definitions available?

**Comment by markwoon** [comment]
Not at the moment. You will need to convert them yourself.

Thanks,
-Mark

**Comment by gpcr** [comment]
thanks for your response. I have B37 converted VCF definitions, Is it works directly with Named allele Matcher or should it be in Json format. if Yes how to convert vcf to Json.

**Comment by markwoon** [comment]
I want to make sure we're talking about the same thing: if your VCF file is using b37, you have 2 choices:

1. convert the named allele definitions (in the cpic-data repo) to b37, or
2. convert your VCF file to b38

The VCF file and the named allele definitions need to both use the same build.  I believe we will eventually release official b37 named allele definitions, but we're still in the middle of validating everything vs. real world data.  There are way too many ways of describing variants, and this will impact how we define variants in the definition files.

**Comment by whaleyr** [comment]
For the upcoming v1.0 release we will only be supporting b38. It will be left to the user to either re-align their samples to b38, liftover their individual calls, or modify the supporting allele definitions themselves and repackage from source.
