### ISSUE TITLE
missing calls - vcf preprocessor issue

### ISSUE THREAD

**Issue by PWSmit** [PharmGKB/PharmCAT#80]
* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
Report states: genotype not called, missing variants found. VCF preprocessor not working correctly? 

* **If the current behavior is a bug, please provide the steps to reproduce and, if possible, your example input data** via a [Gist](https://gist.github.com) or similar.

* **What is the expected behavior?**
input vcf 4.2: 

##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Total number of filtered reads used to call variants at this position in this sample.">
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allele depth, number of filtered reads supporting the alleles, ordered as listed in REF and ALT.">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	Variants_detected_in_detail-Trimmed_sequences-21042939801_S2_L001_(paired,_trimmed_pairs)
1	11790693	.	G	A	.	.	.	GT:AD:DP	0/1:217,0:218
1	11790870	.	C	T	.	.	.	GT:AD:DP	0/1:202,0:202
1	11792243	.	C	G,T	.	.	.	GT:AD:DP	0/1/2:74,0,0:74
1	11794400	.	G	A,C,T	.	.	.	GT:AD:DP	0/1/2/3:0,124,0,0:124
1	11794419	.	T	G	.	.	.	GT:AD:DP	0/1:110,0:110
1	11794614	.	C	A	.	.	.	GT:AD:DP	0/1:115,0:115
1	11796321	.	G	A	.	.	.	GT:AD:DP	0/1:190,1:191
1	11802721	.	A	G	.	.	.	GT:AD:DP	0/1:116,0:116

vcf processor works without error, produces following output in which no calls can be made when used as input for pharmcat: 
##INFO=<ID=PX,Number=.,Type=String,Description="Gene">
##INFO=<ID=POI,Number=0,Type=Flag,Description="Position of Interest but not part of an allele definition">
##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
chr1	97078987	rs114096998;.	G	T	.	.	PX=DPYD;AC=1;AN=3
chr1	97078993	rs148799944;.	C	G	.	.	PX=DPYD;AC=1;AN=2
chr1	97079005	rs140114515;.	C	T	.	.	PX=DPYD;AC=1;AN=2
chr1	97079071	rs1801268;.	C	A	.	.	PX=DPYD;AC=1;AN=2

* **What is the motivation / use case for changing the behavior?**

pharmcat produces no calls

* **Please tell us about your environment:**
  
  - PharmCAT Version: 1.3 - running latest docker environment
  - JDK Version: (docker) openjdk version "16.0.1" 2021-04-20
  - Environment: macOS  

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)

**Comment by BinglanLi** [comment]
This is an issue having to do with the VCF spec. In this case, preprocessor and bcftools are complying with the VCF spec and did the right thing. 
​
Quoting VCF v4.3 spec doc, "_strings in VCF cannot contain ‘,’ (it’s a field separator)_", which means ',' should not be a part of a sample name.
​
On the other hand, removing the "," in your sample name will solve the issue. What happened was that the sample name violated the sample name convention of bcftools by having the comma "," in the sample name. Bcftools considered the "," to be a delimiter of sample names. As a result, bcftools was actually actively looking for two samples named "**_Variants_detected_in_detail-Trimmed_sequences-21042939801_S2_L001_(paired_**" and "**__trimmed_pairs)_**" separately in your VCF, while neither existed in the VCF.
