### ISSUE TITLE
LinkageError?

### ISSUE THREAD

**Issue by joseph-yclam** [PharmGKB/PharmCAT#82]
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
```
Error: LinkageError occurred while loading main class org.pharmgkb.pharmcat.PharmCAT
        java.lang.UnsupportedClassVersionError: org/pharmgkb/pharmcat/PharmCAT has been compiled by a more recent version of the Java Runtime (class file version 58.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

* **If the current behavior is a bug, please provide the steps to reproduce and, if possible, your example input data** via a [Gist](https://gist.github.com) or similar.
1.  Run the command `java -jar "/localhome/PharmCAT-1.2.0/lib/pharmcat-1.2.0-all.jar" -vcf <vcf file here> -o /localhome/PharmCAT-main/PharmCAT_Outputs/ -f pharm_out001 -j -pj
`

* **What is the expected behavior?**
The result should be a JSON and HTML file detailing PharmCAT's output.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - PharmCAT Version: 1.3.0
  - JDK Version: [ JDK17 ]
  - Environment: [ Windows | Linux environment on separate computational server]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)

**Comment by whaleyr** [comment]
You're trying to run PharmCAT using Java 11 when it needs Java 14 or newer.

Specifically, when it says:
> PharmCAT has been compiled by a more recent version of the Java Runtime (class file version 58.0), this version of the Java Runtime only recognizes class file versions up to 55.0

Class file version 58.0 means Java 14 and class file version 55.0 means Java 11. You need to check your environment to make sure you have your java versions installed and linked properly.

Make sure your linux environment has the proper JRE installed. You may need to talk to the sysadmin to request an updated version of the JRE if it's not already installed. If you have access to docker on the system that's also a good tool to ensure you're running a known-good configuration.
