### ISSUE TITLE
Other formats as outputs for beginners 

### ISSUE THREAD

**Issue by Angel7gtgATM** [PharmGKB/PharmCAT#85]
* **Do you want to request a *feature* or report a *bug*?**

FEATURE

* **What is the current behaviour?**

JSON and HTML formats can be recovered as outputs. 

* **What is the motivation / use case for changing the behaviour?**

For novel users that are not related to change formats, it would be great to have both matcher and the "genotype summary" table of the report in TSV format or related. Thanks in advance!!

* **Please tell us about your environment:**
  
  - PharmCAT Version: v1.3.1
  - JDK Version: JDK17 
  - Environment: ubuntu 20.04

**Comment by whaleyr** [comment]
Thanks for your request. We are already discussing TSV internally and should have something available in the not-too-distant future.

When you get the TSV output, are you planning to view it in something like Excel or Google Sheets? Or are you planning on using that TSV as input for another script? Or perhaps both?

**Comment by Angel7gtgATM** [comment]
I am planning to use it in both ways (Excel and as input), also I recommend you build a TSV file very similar to the genotype summary table.

**Comment by whaleyr** [comment]
Thanks for the compliments @Angel7gtgATM, we're happy you find the tool useful.

We've decided to not offer a TSV-formatted output format for the PharmCAT reporter at this time (see #86 for details). If you still want to use TSV I highly encourage you to write your own JSON to TSV parser. JSON is a pretty easy format to learn and work with. You can even use tools like [jq](https://stedolan.github.io/jq/) to transform JSON into other text formats including TSV and you can tailor it to exactly what you want.
