### ISSUE TITLE
Can you add example input vcf and expected output for testing

### ISSUE THREAD

**Issue by gpcr** [PharmGKB/PharmCAT#9]
I am trying to run through NamedAlleleMatcher using grch37 files i generated 

All the out puts says missing.....

Can you add explample files to run and test.
Thanks
........................

There were 38 missing positions from the VCF file:
CYP2C19
Definition Position
VCF Position
VCF REF,ALTs
VCF Call
96535210 (g.96535210G>A)
96521422 (g.96521422G>A)
96522613 (g.96522613A>G)
96541701 (g.96541701G>A)
96520433 (g.96520433C>T)
96522469 (g.96522469C>T)
96522512 (g.96522512T>C)
96540331 (g.96540331G>C)
96541616 (g.96541616G>A)
96612495 (g.96612495C>T)
96612671 (g.96612671A>C)
96535173 (g.96535173T>C)
96602636 (g.96602636G>A)
96535124 (g.96535124A>G)
96520443 (g.96520443C>A)
96540336 (g.96540336G>A)
96522463 (g.96522463A>G)
96609721 (g.96609721A>G)
96535264 (g.96535264G>A)
96534942 (g.96534942A>G)
96540410 (g.96540410G>A)
96521024 (g.96521024T>C)
96534863 (g.96534863C>T)
96602618 (g.96602618G>A)
96541756 (g.96541756T>A)
96522472 (g.96522472T>C)
96522517 (g.96522517A>C)
96522450 (g.96522450G>A)
96609752 (g.96609752C>T)
96612522 (g.96612522C>T)
96541615 (g.96541615C>T)
96535246 (g.96535246G>A)
96602752 (g.96602752G>A)
96521657 (g.96521657C>T)
96534878 (g.96534878C>T)
96522545 (g.96522545A>T)
96534917 (g.96534917G>C)
96612542 (g.96612542C>G)
The following haplotype(s) were eliminated from consideration:

*1
*30
*2
*31
*3
*10
*32
*11
*33
*5
*12
*34
*6
*13
*35
*7
*14
*8
*15
*9
*16
*17
*18
*19
*22
*23
*24
*25
*26
*27
*28
*29
*4A
*4B

**Comment by gpcr** [comment]
It worked after adjusting assembly and other minor fixes in the b37 definition files i created:

PharmCAT Allele Call Report for test.vcf
CFTR
Definition Position	117188682
VCF Position	117188682
VCF REF,ALTs	G,GTT
VCF Call	G/GTT
Reference	G(T)7A
5T	G(T)5A
There were 33 missing positions from the VCF file:

117246808 (g.117246808G>A)
117227860 (g.117227860G>A)
117174372 (g.117174372G>A)
117227865 (g.117227865C>T)
117267591 (g.117267591C>T)
117282620 (g.117282620G>A)
117230494 (g.117230494G>A)
117282537 (g.117282537T>C)
117171029 (g.117171029G>A)
117174420 (g.117174420G>T)
117180284 (g.117180284C>T)
117199645 (g.117199646_117199648delCTT)
117227832 (g.117227832G>T)
117304824 (g.117304824G>A)
117267634 (g.117267635delC)
117171169 (g.117171169G>T)
117242922 (g.117242922G>A)
117227853 (g.117227853A>C)
117227887 (g.117227887G>C)
117227859 (g.117227859G>A)
117232272 (g.117232273delA)
117227855 (g.117227855T>G)
117199644 (g.117199645_117199647delTCT)
117280015 (g.117280015C>T)
117180324 (g.117180324G>C)
117227854 (g.117227854G>A)
117292931 (g.117292931C>G)
117282526 (g.117282526G>A)
117188849 (g.117188849C>A)
117227792 (g.117227792G>A)
117282505 (g.117282505G>A)
117149177 (g.117149177G>A)
117199643 (g.117199644_117199646delATC)
The following haplotype(s) were eliminated from consideration:

2789+5G->A
1717-1G->A
S549R(T>G)
R560T
711+1G->T
S549N
G542X
R334W
1898+1G->A
S1255P
S1251N
621+1G->T
W1282X
G551D
N1303K
R1162X
A455E
3120+1G->A
G85E
F508del(TCT)
G1349D
G551S
F508del(CTT)
3849+10kbC- >T
R553X
G1244E
3659delC
I507
2184delA
R347P
G178R
R117H
S549R(A>C)
CYP2C19
*1/*2 (4)
*2/*35 (3)
Definition Position	96535124	96541616
rs12769205	rs4244285
VCF Position	96535124	96541616
VCF REF,ALTs	A,G	G,A
VCF Call	A/G	G/A
*1	A	G
A	G
*2	[AG]	A
A	A
G	A
*35	G	G
G	G
There were 36 missing positions from the VCF file:

96535210 (g.96535210G>A)
96521422 (g.96521422G>A)
96522613 (g.96522613A>G)
96541701 (g.96541701G>A)
96520433 (g.96520433C>T)
96522469 (g.96522469C>T)
96522512 (g.96522512T>C)
96540331 (g.96540331G>C)
96612495 (g.96612495C>T)
96612671 (g.96612671A>C)
96535173 (g.96535173T>C)
96602636 (g.96602636G>A)
96520443 (g.96520443C>A)
96540336 (g.96540336G>A)
96522463 (g.96522463A>G)
96609721 (g.96609721A>G)
96535264 (g.96535264G>A)
96534942 (g.96534942A>G)
96540410 (g.96540410G>A)
96521024 (g.96521024T>C)
96534863 (g.96534863C>T)
96602618 (g.96602618G>A)
96541756 (g.96541756T>A)
96522472 (g.96522472T>C)
96522517 (g.96522517A>C)
96522450 (g.96522450G>A)
96609752 (g.96609752C>T)
96612522 (g.96612522C>T)
96541615 (g.96541615C>T)
96535246 (g.96535246G>A)
96602752 (g.96602752G>A)
96521657 (g.96521657C>T)
96534878 (g.96534878C>T)
96522545 (g.96522545A>T)
96534917 (g.96534917G>C)
96612542 (g.96612542C>G)
The following haplotype(s) were eliminated from consideration:

*30
*31
*3
*10
*32
*11
*33
*5
*12
*34
*6
*13
*7
*14
*8
*15
*9
*16
*17
*18
*19
*22
*23
*24
*25
*26
*27
*28
*29
*4A
*4B
The following haplotypes were called even though tag positions were missing:

Called *1 without g.96520433C>T, g.96520443C>A, g.96521024T>C, g.96521422G>A, g.96521657C>T, g.96522450G>A, g.96522463A>G, g.96522469C>T, g.96522472T>C, g.96522512T>C, g.96522517A>C, g.96522545A>T, g.96522613A>G, g.96534863C>T, g.96534878C>T, g.96534917G>C, g.96534942A>G, g.96535173T>C, g.96535210G>A, g.96535246G>A, g.96535264G>A, g.96540331G>C, g.96540336G>A, g.96540410G>A, g.96541615C>T, g.96541701G>A, g.96541756T>A, g.96602618G>A, g.96602636G>A, g.96602752G>A, g.96609721A>G, g.96609752C>T, g.96612495C>T, g.96612522C>T, g.96612542C>G, g.96612671A>C
CYP2C9
Definition Position
VCF Position
VCF REF,ALTs
VCF Call
There were 54 missing positions from the VCF file:

96707664 (g.96707664A>C)
96698528 (g.96698528C>T)
96731891 (g.96731891A>G)
96731937 (g.96731937C>G)
96702047 (g.96702047C>T)
96701733 (g.96701733G>C)
96701672 (g.96701672G>A)
96707542 (g.96707542C>T)
96741059 (g.96741059C>A)
96741038 (g.96741038G>A)
96701715 (g.96701715T>C)
96702066 (g.96702066G>A;g.94942309G>T)
96698494 (g.96698494C>A)
96741058 (g.96741058C>G)
96745799 (g.96745799A>G)
96701969 (g.96701970_96701979delAGAAATGGAA)
96707695 (g.96707695A>T)
96748737 (g.96748737A>T)
96708901 (g.96708901C>T)
96748674 (g.96748674G>C)
96701991 (g.96701991G>A)
96702062 (g.96702062G>A)
96748777 (g.96748777C>T)
96707539 (g.96707539C>A)
96701654 (g.96701654G>C)
96702006 (g.96702006C>T;g.94942249C>G)
96707674 (g.96707674T>C)
96701775 (g.96701775T>C)
96702011 (g.96702011C>T)
96741007 (g.96741007C>A)
96741053 (g.96741053A>C)
96701739 (g.96701739G>T)
96731936 (g.96731936A>G)
96709038 (g.96709039delA)
96709037 (g.96709037A>G)
96731876 (g.96731876C>A)
96740982 (g.96740982G>A)
96708886 (g.96708886A>G)
96740981 (g.96740981C>T)
96698440 (g.96698440A>G)
96701988 (g.96701988G>A)
96741122 (g.96741122C>T)
96701973 (g.96701973A>G)
96731990 (g.96731990C>T)
96745830 (g.96745830A>C)
96748780 (g.96748780G>T)
96698585 (g.96698585A>G)
96708974 (g.96708974A>G)
96740958 (g.96740958T>C)
96698560 (g.96698560A>G)
96702012 (g.96702012G>A)
96701987 (g.96701987C>T)
96741054 (g.96741054T>C)
96748741 (g.96748741G>A)
The following haplotype(s) were eliminated from consideration:

*30
*31
*32
*33
*34
*35
*36
*37
*38
*39
*40
*41
*42
*43
*44
*45
*46
*47
*48
*49
*50
*51
*1
*52
*2
*53
*3
*10
*54
*4
*11
*55
*5
*12
*56
*6
*13
*57
*7
*14
*8
*15
*9
*16
*17
*18
*19
*20
*21
*22
*23
*24
*25
*26
*27
*28
*29
CYP3A5
Definition Position
VCF Position
VCF REF,ALTs
VCF Call
There were 8 missing positions from the VCF file:

99262860 (g.99262860T>C)
99258139 (g.99258139C>T)
99270539 (g.99270539T>C)
99264573 (g.99264573A>G)
99262835 (g.99262835C>T)
99250236 (g.99250236G>T)
99250393 (g.99250393_99250394insA)
99273821 (g.99273821G>A)
The following haplotype(s) were eliminated from consideration:

*1
*2
*3
*4
*5
*6
*7
*8
*9
DPYD
*1/*4 (3)
Definition Position	97981421	98348885
rs1801158	rs1801265
VCF Position	97981421	98348885
VCF REF,ALTs	C,T	G,A
VCF Call	C/T	A|A
*1	C	A
C	A
*4	T	A
T	A
There were 13 missing positions from the VCF file:

97915614 (g.97915614C>T)
98205970 (g.98205971_98205974delATGA)
98039499 (g.98039499C>A)
97547947 (g.97547947T>A)
97915621 (g.97915622delG)
97981395 (g.97981395T>C)
97544627 (g.97544627C>A)
98348908 (g.98348908C>T)
97770920 (g.97770920C>T)
97564154 (g.97564154C>T)
98058899 (g.98058899C>A)
98157332 (g.98157332G>A)
97981343 (g.97981343A>C)
The following haplotype(s) were eliminated from consideration:

rs67376798T/A
*2A
*3
*10
*2B
*11
*5
*12
*6
*13
*7
*8
The following haplotypes were called even though tag positions were missing:

Called *1 without g.97544627C>A, g.97547947T>A, g.97564154C>T, g.97770920C>T, g.97915614C>T, g.97915622delG, g.97981343A>C, g.97981395T>C, g.98039499C>A, g.98058899C>A, g.98157332G>A, g.98205971_98205974delATGA, g.98348908C>T
IFNL3
Definition Position
VCF Position
VCF REF,ALTs
VCF Call
There was 1 missing positions from the VCF file:

39738787 (g.39738787C>T)
The following haplotype(s) were eliminated from consideration:

rs12979860C
rs12979860T
SLCO1B1
Definition Position	21329738	21329761	21329813	21331599	21331625
rs2306283	rs11045818	rs11045819	rs4149057	rs2291075
VCF Position	21329738	21329761	21329813	21331599	21331625
VCF REF,ALTs	A,G	G,A	C,A	T,C	C,T
VCF Call	G|G	A|A	A|A	C|C	T|T
*1A	A	G	C	T	C
*1B	G	G	C	T	C
*4	A	G	A	T	C
*14	G	G	A	T	C
*15	G	G	C	T	C
*17	G	G	C	T	C
*18	G	A	A	C	C
*19	A	G	C	C	C
*20	G	G	C	T	T
*21	G	G	C	T	T
*24	G	G	C	T	C
*25	G	G	A	T	C
*27	G	G	C	T	C
*28	G	G	C	T	C
*29	G	G	C	T	C
*30	G	G	C	T	C
*31	G	G	C	T	C
*32	G	G	A	T	C
*33	G	G	C	T	C
*35	G	G	C	T	C
There were 24 missing positions from the VCF file:

21283322 (g.21283322G>A)
21392011 (g.21392011A>G)
21327529 (g.21327529T>C)
21349885 (g.21349885A>G)
21349910 (g.21349910G>A)
21391976 (g.21391976A>C)
21353529 (g.21353529T>C)
21325710 (g.21325710G>A)
21325716 (g.21325716T>C)
21355598 (g.21355598G>A)
21325668 (g.21325668C>T)
21331549 (g.21331549T>C)
21358855 (g.21358855A>G)
21392092 (g.21392092C>T)
21355489 (g.21355489C>G)
21355487 (g.21355487T>G)
21358933 (g.21358933G>C)
21329802 (g.21329802A>G)
21329817 (g.21329817A>G)
21331606 (g.21331606T>G)
21331891 (g.21331891A>G)
21392047 (g.21392047A>G)
21355583 (g.21355583A>G)
21392079 (g.21392079C>T)
The following haplotype(s) were eliminated from consideration:

*2
*3
*10
*11
*22
*5
*12
*23
*34
*6
*13
*7
*36
*8
*26
*9
*16
TPMT
Definition Position	18130918	18139214	18139228
rs1142345	rs2842934	rs1800460
VCF Position	18130918	18139214	18139228
VCF REF,ALTs	T,C	G,A	C,T
VCF Call	T/C	A|A	C/T
*1	T	G	C
*1S	T	A	C
*3A	C	G	T
*3B	T	G	T
*3C	C	G	C
There were 28 missing positions from the VCF file:

18131003 (g.18131003A>G)
18134121 (g.18134121C>T)
18139258 (g.18139258C>G)
18149235 (g.18149235G>C)
18131012 (g.18131012C>T)
18148141 (g.18148141A>G)
18143844 (g.18143844C>G)
18149357 (g.18149357A>G)
18134078 (g.18134078C>A)
18134076 (g.18134076T>A)
18134115 (g.18134115G>C)
18132378 (g.18132378A>G)
18130956 (g.18130956A>C)
18149276 (g.18149276T>A)
18143955 (g.18143955C>G)
18148076 (g.18148076C>T)
18132367 (g.18132367A>G)
18130993 (g.18130993C>T)
18139920 (g.18139920C>T)
18130925 (g.18130925T>C)
18143828 (g.18143828T>G)
18143874 (g.18143874A>C)
18139200 (g.18139200C>T; g.18138969C>G)
18148082 (g.18148082G>C)
18143837 (g.18143837T>G)
18139941 (g.18139941G>A)
18149358 (g.18149358T>C)
18149253 (g.18149253C>T)
The following haplotype(s) were eliminated from consideration:

*30
*2
*31
*10
*4
*11
*5
*12
*6
*13
*7
*14
*8
*15
*9
*16
*17
*18
*19
*20
*21
*22
*23
*24
*25
*26
*27
*28
*29
UGT1A1
Definition Position
VCF Position
VCF REF,ALTs
VCF Call
There were 5 missing positions from the VCF file:

234668570 (g.234668570C>T)
234665659 (g.234665659T>G)
234668880 (g.234668880)
234669144 (g.234669144G>A)
234669619 (g.234669619C>A)
The following haplotype(s) were eliminated from consideration:

*28
*80
*60
*1
*6
*36
*37
*27
VKORC1
-1639A/-1639G (2)
Definition Position	31107689
rs9923231
VCF Position	31107689
VCF REF,ALTs	C,T
VCF Call	C/T
-1639A	T
T
-1639G	C
C
Generated on 08/07/16.

**Comment by markwoon** [comment]
From your last comment it sounds like you figured out the problem.  Can I close this issue?

**Comment by gpcr** [comment]
Yes, you can close....Thanks for responses....
