### ISSUE TITLE
How to use Astrolabe's output and pipe it into  PharmCAT?

### ISSUE THREAD

**Issue by joseph-yclam** [PharmGKB/PharmCAT#96]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
I am having issues with trying to use Astrolabe's outputs to call CYP2D6 star alleles using PharmCAT. I have attempted the following command lines with their respective, erroneous outputs:
Input using:
`java -jar /localhome/PharmCAT-1.3.0/lib/pharmcat-1.3.0-all.jar -vcf /export/CIM_output/BAM_hg38/pharmvar_input/CIM001.pharmact.input.vcf -a /localhome/joseph.lam1/astrolabe-0.8.7.2/astro_output/astro_out001 -o /localhome/joseph.lam1/PharmCAT-1.3.0/PharmCAT_Outputs -f pharm_out001`

Yields:
![image](https://user-images.githubusercontent.com/76238646/158088561-feea87db-ffea-47fb-bad9-7cc0a32874e5.png)

As well, input using:
`java -jar /localhome/PharmCAT-1.3.0/lib/pharmcat-1.3.0-all.jar -vcf /export/CIM_output/BAM_hg38/pharmvar_input/CIM001.pharmact.input.vcf -a /localhome/joseph.lam1/astrolabe-0.8.7.2/etc/GRCh38/CYP2D6/locationData.tsv -o /localhome/joseph.lam1/PharmCAT-1.3.0/PharmCAT_Outputs -f pharm_out001
`

Yields:
![image](https://user-images.githubusercontent.com/76238646/158089683-5d6494b2-ab95-4f0a-94a3-782d59af1b22.png)

I am planning to run this on multiple samples but I am unsure how to use Astrolabe's output?

* **What is the expected behavior?**
The expected behavior would be to perform phenotype prediction and subsequent drug dosing recommendation based off of Astrolabe's output for CYP2D6

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - PharmCAT Version: 1.3.0
  - JDK Version: [DK8
  - Environment: Windows

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)

**Comment by whaleyr** [comment]
First: I recommend you grab [the most recent version of PharmCAT](https://github.com/PharmGKB/PharmCAT/releases/latest) and use that (v1.5.1 at this time).

Second: from the error message, it looks like your sample data includes positions for CYP4F2 and you're also specifying a call from the outside call file (astrolabe). We're doing some work on the outside call component so it's a little volatile at the moment, but currently you have to supply one or other other. This may change but for now that's the way it's working. So take the CYP4F2 positions out of the sample file or take the call out of the astrolabe file and then try re-running it and that should do it. Please let me know how it goes.

**Comment by joseph-yclam** [comment]
Thank you so much for your response! I'm sorry, just to clarify, when you say I have to supply one or the other, you mean I have to supply either the sample file OR the call from the outside call file, right? And, in that case, since I want to use Astrolabe's call sample to determine CYP2D6 calls for PharmCAT, I would just use Astrolabe's outside call file?

**Comment by whaleyr** [comment]
You can supply both input files. However, if you supply CYP2D6 variants in the VCF file, don't include a CYP2D6 call in the outside caller TSV file. Conversely, if you supply a CYP2D6 call in the outside caller TSV file, don't supply CYP2D6 positions in the VCF file.

**Comment by markwoon** [comment]
We've updated documentation on this: https://pharmcat.org/using/Outside-Call-Format/

If that's not sufficient for your needs, please open a new issue with details.
